// Generated from: features\Calendar.feature
import { test } from "playwright-bdd";

test.describe('Calendar Module - View, Navigate and  Activities', () => {

  test.beforeEach('Background', async ({ Given, And }, testInfo) => { if (testInfo.error) return;
    await Given('the user is logged into the SuitCRM'); 
    await And('the user navigates to the "Calendar" module in the menu'); 
  });
  
  test('Verify the Calendar top navigation menu is displayed', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('the user views the top navigation bar'); 
    await Then('the menu items "Calendar", "Accounts", "Contacts", "Opportunities", "Leads", "Quotes", "Documents" and "More" are displayed'); 
  });

  test('Verify the "calendar" icon.', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is logged into the SuitCRM'); 
    await When('the user hovers over the "calendar" icon in the top navigation bar'); 
    await Then('user should see the "Schedule Meeting", "Schedule Call", "Create Task" and "Today" options in the dropdown menu'); 
  });

  test('Veryfy the calendar  items.', { tag: ['@calendar'] }, async ({ When, Then }) => { 
    await When('the user clicks the "calendar" icon'); 
    await Then('the user should be navigated to "Calendar" Dashboard page and should see the buttons.', {"dataTable":{"rows":[{"cells":[{"value":"Day"}]},{"cells":[{"value":"Week"}]},{"cells":[{"value":"Month"}]},{"cells":[{"value":"Shared Month"}]},{"cells":[{"value":"Shared Week"}]},{"cells":[{"value":"Settings"}]},{"cells":[{"value":"Calendar icon"}]}]}}); 
  });

  test('Verify selecting Schedule Meeting opens the meeting creation form', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has opened the "Calendar" dropdown menu'); 
    await When('the user clicks "Schedule Meeting"'); 
    await Then('User should see the "Schedule Meeting"  component .', {"dataTable":{"rows":[{"cells":[{"value":"component"},{"value":"expected value"}]},{"cells":[{"value":"Page Title"},{"value":"MEETING CREATE"}]},{"cells":[{"value":"Buttons"},{"value":"Save, Cancel,Save & Send Invites, Close And Create New,Search"}]}]}}); 
  });

  test.describe('Validate error on saving Shedule Meeting Page with a mandatory field left blank', () => {

    test('Example #1', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then, And }) => { 
      await Given('the user is on the "Schedule Meeting" page'); 
      await When('the user leaves the "Subject" field blank and clicks "Save"'); 
      await Then('a validation message is displayed "Missing required field: Subject"'); 
      await And('the survey is not saved'); 
    });

    test('Example #2', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then, And }) => { 
      await Given('the user is on the "Schedule Meeting" page'); 
      await When('the user leaves the "Start Date" field blank and clicks "Save"'); 
      await Then('a validation message is displayed "Missing required field: Start Date"'); 
      await And('the survey is not saved'); 
    });

    test('Example #3', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then, And }) => { 
      await Given('the user is on the "Schedule Meeting" page'); 
      await When('the user leaves the "End Date" field blank and clicks "Save"'); 
      await Then('a validation message is displayed "Missing required field: End Date"'); 
      await And('the survey is not saved'); 
    });

  });

  test('Verify selecting Schedule Call opens the call creation form', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has opened the "Calendar" dropdown menu'); 
    await When('the user clicks "Schedule Call"'); 
    await Then('the "Schedule Call" form is displayed with components', {"dataTable":{"rows":[{"cells":[{"value":"component"},{"value":"expected value"}]},{"cells":[{"value":"Page Title"},{"value":"CALL CREATE"}]},{"cells":[{"value":"Buttons"},{"value":"Save, Cancel,Save & Send Invites, Close And Create New,Search"}]}]}}); 
  });

  test.describe('Validate error on saving Shedule Call Page with a mandatory field left blank', () => {

    test('Example #1', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then, And }) => { 
      await Given('the user is on the "Schedule Call" page'); 
      await When('the user leaves the "Subject" field blank and clicks "Save"'); 
      await Then('a validation message is displayed "Missing required field: Subject"'); 
      await And('the survey is not saved'); 
    });

    test('Example #2', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then, And }) => { 
      await Given('the user is on the "Schedule Call" page'); 
      await When('the user leaves the "Start Date" field blank and clicks "Save"'); 
      await Then('a validation message is displayed "Missing required field: Start Date"'); 
      await And('the survey is not saved'); 
    });

    test('Example #3', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then, And }) => { 
      await Given('the user is on the "Schedule Call" page'); 
      await When('the user leaves the "End Date" field blank and clicks "Save"'); 
      await Then('a validation message is displayed "Missing required field: End Date"'); 
      await And('the survey is not saved'); 
    });

  });

  test('Verify selecting Create Task opens the task creation form', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has opened the "Calendar" dropdown menu'); 
    await When('the user clicks "Create Task"'); 
    await Then('a new "Create Task" form is displayed with components', {"dataTable":{"rows":[{"cells":[{"value":"component"},{"value":"expected value"}]},{"cells":[{"value":"Page Title"},{"value":"TASK CREATE"}]},{"cells":[{"value":"Buttons"},{"value":"Save, Cancel,Save & Send Invites, Close And Create New,Search"}]}]}}); 
  });

  test.describe('Validate error on saving Create Task Page with a mandatory field left blank', () => {

    test('Example #1', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then, And }) => { 
      await Given('the user is on the "Create Task" page'); 
      await When('the user leaves the "Subject" field blank and clicks "Save"'); 
      await Then('a validation message is displayed "Missing required field: Subject"'); 
      await And('the survey is not saved'); 
    });

    test('Example #2', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then, And }) => { 
      await Given('the user is on the "Create Task" page'); 
      await When('the user leaves the "Start Date" field blank and clicks "Save"'); 
      await Then('a validation message is displayed "Missing required field: Start Date"'); 
      await And('the survey is not saved'); 
    });

    test('Example #3', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then, And }) => { 
      await Given('the user is on the "Create Task" page'); 
      await When('the user leaves the "End Date" field blank and clicks "Save"'); 
      await Then('a validation message is displayed "Missing required field: End Date"'); 
      await And('the survey is not saved'); 
    });

  });

  test('Verify  "Today" page open.', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has opened the "Calendar" dropdown menu'); 
    await When('the user opens the "Calendar" dropdown menu and clicks "Today"'); 
    await Then('the calendar refreshes to display the  current date activities with buttons "Day", "Week", "Month", "Shared Month", "Shared Week", "Settings" and "Calendar icon" are displayed'); 
  });

  test('Verify the assigned user name is displayed above the calendar grid', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Today" view'); 
    await When('the user views the row directly above the day column headers'); 
    await Then('the assigned user\'s name is displayed'); 
  });

  test('checking CREATE ACTIVITY popup window shows.', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Today" view'); 
    await When('the user clicks the cell corresponding to a specific time slot in the calendar grid'); 
    await Then('a popup window appears with options to create a new activity, including fields for "Subject", "Start Date", "End Date"'); 
  });

  test('Saved activity appears on the calendar grid in its time slot', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('the calendar is loaded in "Today" view'); 
    await When('the user clicks the cell corresponding to a specific time slot in the calendar grid'); 
    await And('the user enters a valid value in the "Subject" field'); 
    await And('the user clicks the "Save" button'); 
    await Then('the popup closes'); 
    await And('the activity appears in the calendar cell at the corresponding time slot'); 
    await And('the cell displays the start time and the assigned user\'s name'); 
  });

  test('Verify the calendar grid loads within an acceptable time (Performance)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the user navigates to the Calendar module'); 
    await When('the calendar page is requested'); 
    await Then('the full week grid, including all day columns and hourly rows, renders within 2 to 5 seconds'); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features\\Calendar.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":11,"pickleLine":10,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":11,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user views the top navigation bar","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the menu items \"Calendar\", \"Accounts\", \"Contacts\", \"Opportunities\", \"Leads\", \"Quotes\", \"Documents\" and \"More\" are displayed","stepMatchArguments":[{"group":{"start":15,"value":"\"Calendar\"","children":[{"start":16,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":27,"value":"\"Accounts\"","children":[{"start":28,"value":"Accounts","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Contacts\"","children":[{"start":40,"value":"Contacts","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"Opportunities\"","children":[{"start":52,"value":"Opportunities","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"Leads\"","children":[{"start":69,"value":"Leads","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":77,"value":"\"Quotes\"","children":[{"start":78,"value":"Quotes","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":87,"value":"\"Documents\"","children":[{"start":88,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":103,"value":"\"More\"","children":[{"start":104,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":17,"pickleLine":17,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":18,"gherkinStepLine":18,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","stepMatchArguments":[]},{"pwStepLine":19,"gherkinStepLine":19,"keywordType":"Action","textWithKeyword":"When the user hovers over the \"calendar\" icon in the top navigation bar","stepMatchArguments":[{"group":{"start":25,"value":"\"calendar\"","children":[{"start":26,"value":"calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":20,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"Then user should see the \"Schedule Meeting\", \"Schedule Call\", \"Create Task\" and \"Today\" options in the dropdown menu","stepMatchArguments":[{"group":{"start":20,"value":"\"Schedule Meeting\"","children":[{"start":21,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Schedule Call\"","children":[{"start":41,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":57,"value":"\"Create Task\"","children":[{"start":58,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":75,"value":"\"Today\"","children":[{"start":76,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":23,"pickleLine":22,"tags":["@calendar"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When the user clicks the \"calendar\" icon","stepMatchArguments":[{"group":{"start":20,"value":"\"calendar\"","children":[{"start":21,"value":"calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then the user should be navigated to \"Calendar\" Dashboard page and should see the buttons.","stepMatchArguments":[{"group":{"start":32,"value":"\"Calendar\"","children":[{"start":33,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":28,"pickleLine":37,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":38,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"When the user clicks \"Schedule Meeting\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Schedule Meeting\"","children":[{"start":17,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"Schedule Meeting\"  component .","stepMatchArguments":[{"group":{"start":20,"value":"\"Schedule Meeting\"","children":[{"start":21,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":36,"pickleLine":58,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":51,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Meeting\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Meeting\"","children":[{"start":20,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":52,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Subject\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Subject\"","children":[{"start":21,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"Save\"","children":[{"start":54,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":53,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Subject\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Subject\"","children":[{"start":35,"value":"Missing required field: Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":40,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"And the survey is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":43,"pickleLine":59,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":51,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Meeting\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Meeting\"","children":[{"start":20,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":52,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Start Date\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Start Date\"","children":[{"start":21,"value":"Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"Save\"","children":[{"start":57,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":53,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Start Date\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Start Date\"","children":[{"start":35,"value":"Missing required field: Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":47,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"And the survey is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":50,"pickleLine":60,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":51,"gherkinStepLine":51,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Meeting\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Meeting\"","children":[{"start":20,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":52,"keywordType":"Action","textWithKeyword":"When the user leaves the \"End Date\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"End Date\"","children":[{"start":21,"value":"End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"Save\"","children":[{"start":55,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":53,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: End Date\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: End Date\"","children":[{"start":35,"value":"Missing required field: End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"And the survey is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":59,"pickleLine":64,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":60,"gherkinStepLine":65,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":66,"keywordType":"Action","textWithKeyword":"When the user clicks \"Schedule Call\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Schedule Call\"","children":[{"start":17,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"Then the \"Schedule Call\" form is displayed with components","stepMatchArguments":[{"group":{"start":4,"value":"\"Schedule Call\"","children":[{"start":5,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":67,"pickleLine":84,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Call\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Call\"","children":[{"start":20,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":78,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Subject\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Subject\"","children":[{"start":21,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"Save\"","children":[{"start":54,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":79,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Subject\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Subject\"","children":[{"start":35,"value":"Missing required field: Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"And the survey is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":74,"pickleLine":85,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Call\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Call\"","children":[{"start":20,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":76,"gherkinStepLine":78,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Start Date\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Start Date\"","children":[{"start":21,"value":"Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"Save\"","children":[{"start":57,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":77,"gherkinStepLine":79,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Start Date\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Start Date\"","children":[{"start":35,"value":"Missing required field: Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"And the survey is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":81,"pickleLine":86,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Call\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Call\"","children":[{"start":20,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":83,"gherkinStepLine":78,"keywordType":"Action","textWithKeyword":"When the user leaves the \"End Date\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"End Date\"","children":[{"start":21,"value":"End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"Save\"","children":[{"start":55,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":84,"gherkinStepLine":79,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: End Date\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: End Date\"","children":[{"start":35,"value":"Missing required field: End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":85,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"And the survey is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":90,"pickleLine":90,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":91,"gherkinStepLine":91,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":92,"gherkinStepLine":92,"keywordType":"Action","textWithKeyword":"When the user clicks \"Create Task\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Create Task\"","children":[{"start":17,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":93,"keywordType":"Outcome","textWithKeyword":"Then a new \"Create Task\" form is displayed with components","stepMatchArguments":[{"group":{"start":6,"value":"\"Create Task\"","children":[{"start":7,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":98,"pickleLine":112,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":99,"gherkinStepLine":105,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Task\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Task\"","children":[{"start":20,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":100,"gherkinStepLine":106,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Subject\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Subject\"","children":[{"start":21,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"Save\"","children":[{"start":54,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":101,"gherkinStepLine":107,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Subject\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Subject\"","children":[{"start":35,"value":"Missing required field: Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":102,"gherkinStepLine":108,"keywordType":"Outcome","textWithKeyword":"And the survey is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":105,"pickleLine":113,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":105,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Task\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Task\"","children":[{"start":20,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":107,"gherkinStepLine":106,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Start Date\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Start Date\"","children":[{"start":21,"value":"Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"Save\"","children":[{"start":57,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":108,"gherkinStepLine":107,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Start Date\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Start Date\"","children":[{"start":35,"value":"Missing required field: Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":109,"gherkinStepLine":108,"keywordType":"Outcome","textWithKeyword":"And the survey is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":112,"pickleLine":114,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":113,"gherkinStepLine":105,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Task\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Task\"","children":[{"start":20,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":114,"gherkinStepLine":106,"keywordType":"Action","textWithKeyword":"When the user leaves the \"End Date\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"End Date\"","children":[{"start":21,"value":"End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"Save\"","children":[{"start":55,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":115,"gherkinStepLine":107,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: End Date\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: End Date\"","children":[{"start":35,"value":"Missing required field: End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":116,"gherkinStepLine":108,"keywordType":"Outcome","textWithKeyword":"And the survey is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":121,"pickleLine":118,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":122,"gherkinStepLine":119,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":123,"gherkinStepLine":120,"keywordType":"Action","textWithKeyword":"When the user opens the \"Calendar\" dropdown menu and clicks \"Today\"","stepMatchArguments":[{"group":{"start":19,"value":"\"Calendar\"","children":[{"start":20,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":55,"value":"\"Today\"","children":[{"start":56,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":124,"gherkinStepLine":121,"keywordType":"Outcome","textWithKeyword":"Then the calendar refreshes to display the  current date activities with buttons \"Day\", \"Week\", \"Month\", \"Shared Month\", \"Shared Week\", \"Settings\" and \"Calendar icon\" are displayed","stepMatchArguments":[{"group":{"start":76,"value":"\"Day\"","children":[{"start":77,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":83,"value":"\"Week\"","children":[{"start":84,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":91,"value":"\"Month\"","children":[{"start":92,"value":"Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":100,"value":"\"Shared Month\"","children":[{"start":101,"value":"Shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":116,"value":"\"Shared Week\"","children":[{"start":117,"value":"Shared Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":131,"value":"\"Settings\"","children":[{"start":132,"value":"Settings","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":146,"value":"\"Calendar icon\"","children":[{"start":147,"value":"Calendar icon","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":127,"pickleLine":124,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":128,"gherkinStepLine":125,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Today\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Today\"","children":[{"start":27,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":129,"gherkinStepLine":126,"keywordType":"Action","textWithKeyword":"When the user views the row directly above the day column headers","stepMatchArguments":[]},{"pwStepLine":130,"gherkinStepLine":127,"keywordType":"Outcome","textWithKeyword":"Then the assigned user's name is displayed","stepMatchArguments":[]}]},
  {"pwTestLine":133,"pickleLine":130,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":134,"gherkinStepLine":131,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Today\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Today\"","children":[{"start":27,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":135,"gherkinStepLine":132,"keywordType":"Action","textWithKeyword":"When the user clicks the cell corresponding to a specific time slot in the calendar grid","stepMatchArguments":[]},{"pwStepLine":136,"gherkinStepLine":133,"keywordType":"Outcome","textWithKeyword":"Then a popup window appears with options to create a new activity, including fields for \"Subject\", \"Start Date\", \"End Date\"","stepMatchArguments":[{"group":{"start":83,"value":"\"Subject\"","children":[{"start":84,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":94,"value":"\"Start Date\"","children":[{"start":95,"value":"Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":108,"value":"\"End Date\"","children":[{"start":109,"value":"End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":139,"pickleLine":136,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":140,"gherkinStepLine":137,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Today\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Today\"","children":[{"start":27,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":141,"gherkinStepLine":138,"keywordType":"Action","textWithKeyword":"When the user clicks the cell corresponding to a specific time slot in the calendar grid","stepMatchArguments":[]},{"pwStepLine":142,"gherkinStepLine":139,"keywordType":"Action","textWithKeyword":"And the user enters a valid value in the \"Subject\" field","stepMatchArguments":[{"group":{"start":37,"value":"\"Subject\"","children":[{"start":38,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":143,"gherkinStepLine":140,"keywordType":"Action","textWithKeyword":"And the user clicks the \"Save\" button","stepMatchArguments":[{"group":{"start":20,"value":"\"Save\"","children":[{"start":21,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":144,"gherkinStepLine":141,"keywordType":"Outcome","textWithKeyword":"Then the popup closes","stepMatchArguments":[]},{"pwStepLine":145,"gherkinStepLine":142,"keywordType":"Outcome","textWithKeyword":"And the activity appears in the calendar cell at the corresponding time slot","stepMatchArguments":[]},{"pwStepLine":146,"gherkinStepLine":143,"keywordType":"Outcome","textWithKeyword":"And the cell displays the start time and the assigned user's name","stepMatchArguments":[]}]},
  {"pwTestLine":149,"pickleLine":146,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":150,"gherkinStepLine":147,"keywordType":"Context","textWithKeyword":"Given the user navigates to the Calendar module","stepMatchArguments":[]},{"pwStepLine":151,"gherkinStepLine":148,"keywordType":"Action","textWithKeyword":"When the calendar page is requested","stepMatchArguments":[]},{"pwStepLine":152,"gherkinStepLine":149,"keywordType":"Outcome","textWithKeyword":"Then the full week grid, including all day columns and hourly rows, renders within 2 to 5 seconds","stepMatchArguments":[{"group":{"start":78,"value":"2"},"parameterTypeName":"int"},{"group":{"start":83,"value":"5"},"parameterTypeName":"int"}]}]},
]; // bdd-data-end