// Generated from: features/Calendar.feature
import { test } from "../../fixtures/suite8Fixtures.js";

test.describe('Calendar Module - View, Navigate and  Activities', () => {

  test.beforeEach('Background', async ({ Given, And, calendarPage, page }, testInfo) => { if (testInfo.error) return;
    await Given('the user is logged into the SuitCRM', null, { page }); 
    await And('the user navigates to the "Calendar" module in the menu', null, { calendarPage, page }); 
  });
  
  test('Verify the "calendar" icon.', { tag: ['@calendar', '@functional', '@calendarIcon'] }, async ({ When, Then, calendarPage }) => { 
    await When('the user hovers over the "calendar" icon in the top navigation bar', null, { calendarPage }); 
    await Then('user should see the "Schedule Meeting", "Schedule Call", "Create Task" and "Today" options in the dropdown menu', null, { calendarPage }); 
  });

  test('Verify the calendar  items.', { tag: ['@calendar', '@functional', '@calendarItem'] }, async ({ When, Then, calendarPage }) => { 
    await When('the user clicks the "calendar" icon', null, { calendarPage }); 
    await Then('the user should be navigated to "Calendar" Dashboard page and should see the buttons.', {"dataTable":{"rows":[{"cells":[{"value":"Day"}]},{"cells":[{"value":"Week"}]},{"cells":[{"value":"Month"}]},{"cells":[{"value":"Shared Month"}]},{"cells":[{"value":"Shared Week"}]},{"cells":[{"value":"Settings"}]},{"cells":[{"value":"Calendar icon"}]}]}}, { calendarPage }); 
  });

  test('Verify selecting Schedule Meeting opens the meeting creation form', { tag: ['@calendar', '@functional', '@scheduledMeeting'] }, async ({ Given, When, Then, calendarPage }) => { 
    await Given('the user has opened the "Calendar" dropdown menu', null, { calendarPage }); 
    await When('the user clicks "Schedule Meeting"', null, { calendarPage }); 
    await Then('User should see the "Schedule Meeting" component.', {"dataTable":{"rows":[{"cells":[{"value":"component"},{"value":"expected value"}]},{"cells":[{"value":"Page Title"},{"value":"MEETINGS CREATE"}]},{"cells":[{"value":"Buttons"},{"value":"Save, Cancel,Save & Send Invites, Close and Create New,Search"}]}]}}, { calendarPage }); 
  });

  test.describe('Validate error on saving Schedule Meeting Page with a mandatory field left blank', () => {

    test('Example #1', { tag: ['@calendar', '@negative', '@scheduledMeetingnegative'] }, async ({ Given, When, Then, And, calendarPage, page }) => { 
      await Given('the user is on the "Schedule Meeting" page', null, { calendarPage, page }); 
      await When('the user leaves the "Subject" field blank and clicks "Save"', null, { calendarPage }); 
      await Then('a validation message is displayed "Missing required field: Subject"', null, { calendarPage }); 
      await And('the meeting is not saved', null, { calendarPage }); 
    });

    test('Example #2', { tag: ['@calendar', '@negative', '@scheduledMeetingnegative'] }, async ({ Given, When, Then, And, calendarPage, page }) => { 
      await Given('the user is on the "Schedule Meeting" page', null, { calendarPage, page }); 
      await When('the user leaves the "Start Date" field blank and clicks "Save"', null, { calendarPage }); 
      await Then('a validation message is displayed "Missing required field: Start Date"', null, { calendarPage }); 
      await And('the meeting is not saved', null, { calendarPage }); 
    });

    test('Example #3', { tag: ['@calendar', '@negative', '@scheduledMeetingnegative'] }, async ({ Given, When, Then, And, calendarPage, page }) => { 
      await Given('the user is on the "Schedule Meeting" page', null, { calendarPage, page }); 
      await When('the user leaves the "End Date" field blank and clicks "Save"', null, { calendarPage }); 
      await Then('a validation message is displayed "Missing required field: End Date"', null, { calendarPage }); 
      await And('the meeting is not saved', null, { calendarPage }); 
    });

  });

  test('Verify selecting Schedule Call opens the call creation form', { tag: ['@calendar', '@functional', '@scheduledCall'] }, async ({ Given, When, Then, calendarPage }) => { 
    await Given('the user has opened the "Calendar" dropdown menu', null, { calendarPage }); 
    await When('the user clicks "Schedule Call"', null, { calendarPage }); 
    await Then('the "Schedule Call" form is displayed with components', {"dataTable":{"rows":[{"cells":[{"value":"component"},{"value":"expected value"}]},{"cells":[{"value":"Page Title"},{"value":"CALL CREATE"}]},{"cells":[{"value":"Buttons"},{"value":"Save, Cancel,Save & Send Invites, Close and Create New,Search"}]}]}}, { calendarPage }); 
  });

  test.describe('Validate error on saving Shedule Call Page with a mandatory field left blank', () => {

    test('Example #1', { tag: ['@calendar', '@negative', '@scheduledCallNegative'] }, async ({ Given, When, Then, And, calendarPage, page }) => { 
      await Given('the user is on the "Schedule Call" page', null, { calendarPage, page }); 
      await When('the user leaves the "Subject" field blank and clicks "Save"', null, { calendarPage }); 
      await Then('a validation message is displayed "Missing required field: Subject"', null, { calendarPage }); 
      await And('the meeting is not saved', null, { calendarPage }); 
    });

    test('Example #2', { tag: ['@calendar', '@negative', '@scheduledCallNegative'] }, async ({ Given, When, Then, And, calendarPage, page }) => { 
      await Given('the user is on the "Schedule Call" page', null, { calendarPage, page }); 
      await When('the user leaves the "Start Date & Time" field blank and clicks "Save"', null, { calendarPage }); 
      await Then('a validation message is displayed "Missing required field: Start Date"', null, { calendarPage }); 
      await And('the meeting is not saved', null, { calendarPage }); 
    });

    test('Example #3', { tag: ['@calendar', '@negative', '@scheduledCallNegative'] }, async ({ Given, When, Then, And, calendarPage, page }) => { 
      await Given('the user is on the "Schedule Call" page', null, { calendarPage, page }); 
      await When('the user leaves the "Duration" field blank and clicks "Save"', null, { calendarPage }); 
      await Then('a validation message is displayed "Missing required field: Duration"', null, { calendarPage }); 
      await And('the meeting is not saved', null, { calendarPage }); 
    });

  });

  test('Verify selecting Create Task components', { tag: ['@calendar', '@functional', '@creatTask'] }, async ({ Given, When, Then, calendarPage }) => { 
    await Given('the user has opened the "Calendar" dropdown menu', null, { calendarPage }); 
    await When('the user clicks "Create Task"', null, { calendarPage }); 
    await Then('a new "Create Task" form is displayed with components', {"dataTable":{"rows":[{"cells":[{"value":"component"},{"value":"expected value"}]},{"cells":[{"value":"Page Title"},{"value":"CREATE"}]},{"cells":[{"value":"Buttons"},{"value":"Save, Cancel"}]}]}}, { calendarPage }); 
  });

  test.describe('Validate error on saving Create Task Page with a mandatory field left blank', () => {

    test('Example #1', { tag: ['@calendar', '@negative', '@createTaskNegative'] }, async ({ Given, When, Then, And, calendarPage, page }) => { 
      await Given('the user is on the "Create Task" page', null, { calendarPage, page }); 
      await When('the user leaves the "Subject" field blank and clicks "Save"', null, { calendarPage }); 
      await Then('a validation message is displayed "Missing required field: Subject"', null, { calendarPage }); 
      await And('the meeting is not saved', null, { calendarPage }); 
    });

    test('Example #2', { tag: ['@calendar', '@negative', '@createTaskNegative'] }, async ({ Given, When, Then, And, calendarPage, page }) => { 
      await Given('the user is on the "Create Task" page', null, { calendarPage, page }); 
      await When('the user leaves the "Priority" field blank and clicks "Save"', null, { calendarPage }); 
      await Then('a validation message is displayed "Missing required field: Priority"', null, { calendarPage }); 
      await And('the meeting is not saved', null, { calendarPage }); 
    });

  });

  test('Verify  "Today" page open and buttons are vissible', { tag: ['@calendar', '@functional', '@todayView'] }, async ({ Given, When, Then, calendarPage }) => { 
    await Given('the user has opened the "Calendar" dropdown menu', null, { calendarPage }); 
    await When('the user opens the "Calendar" dropdown menu and clicks "Today"', null, { calendarPage }); 
    await Then('the calendar refreshes to display the  current date activities with buttons "Day", "Week", "Month", "Shared Month", "Shared Week", "Settings" and "Calendar icon" are displayed', null, { calendarPage }); 
  });

  test('Verify the assigned user name is displayed above the calendar grid', { tag: ['@calendar', '@functional', '@assignedUser'] }, async ({ Given, When, Then, calendarPage, page }) => { 
    await Given('the calendar is loaded in "Today" view', null, { calendarPage, page }); 
    await When('the user views the row directly above the day column headers'); 
    await Then('the assigned user\'s name is displayed', null, { calendarPage }); 
  });

  test('checking CREATE ACTIVITY popup window shows.', { tag: ['@calendar', '@functional', '@createActivityPopup'] }, async ({ Given, When, Then, calendarPage, page }) => { 
    await Given('the calendar is loaded in "Today" view', null, { calendarPage, page }); 
    await When('the user click the cell corresponding to a specific time slot in the calendar grid', null, { calendarPage }); 
    await Then('a popup window appears with options to create a new activity, including fields for "Subject", "Start Date", "End Date"', null, { calendarPage }); 
  });

  test('Saved activity appears on the calendar grid in its time slot', { tag: ['@calendar', '@functional', '@savedActivity'] }, async ({ Given, When, Then, And, calendarPage, page }) => { 
    await Given('the calendar is loaded in "Today" view', null, { calendarPage, page }); 
    await When('the user click the cell corresponding to a specific time slot in the calendar grid', null, { calendarPage }); 
    await And('the user enters a valid value in the "Subject", "Start Date", "End Date"', null, { calendarPage }); 
    await And('the user clicks the "Save" button', null, { calendarPage }); 
    await Then('the popup closes', null, { calendarPage }); 
    await And('the activity appears in the calendar cell at the corresponding time slot', null, { calendarPage }); 
    await And('the cell displays the start time and the assigned user\'s name', null, { calendarPage }); 
    await And('the user deletes the saved activity', null, { calendarPage }); 
  });

});

// == technical section ==

test.beforeEach('BeforeEach Hooks', ({ $runScenarioHooks, page }) => $runScenarioHooks('before', { page }));
test.afterEach('AfterEach Hooks', ({ $runScenarioHooks, page }) => $runScenarioHooks('after', { page }));

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/Calendar.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":11,"pickleLine":17,"tags":["@calendar","@functional","@calendarIcon"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":18,"keywordType":"Action","textWithKeyword":"When the user hovers over the \"calendar\" icon in the top navigation bar","stepMatchArguments":[{"group":{"start":25,"value":"\"calendar\"","children":[{"start":26,"value":"calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then user should see the \"Schedule Meeting\", \"Schedule Call\", \"Create Task\" and \"Today\" options in the dropdown menu","stepMatchArguments":[{"group":{"start":20,"value":"\"Schedule Meeting\"","children":[{"start":21,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Schedule Call\"","children":[{"start":41,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":57,"value":"\"Create Task\"","children":[{"start":58,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":75,"value":"\"Today\"","children":[{"start":76,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":16,"pickleLine":22,"tags":["@calendar","@functional","@calendarItem"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When the user clicks the \"calendar\" icon","stepMatchArguments":[{"group":{"start":20,"value":"\"calendar\"","children":[{"start":21,"value":"calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":18,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then the user should be navigated to \"Calendar\" Dashboard page and should see the buttons.","stepMatchArguments":[{"group":{"start":32,"value":"\"Calendar\"","children":[{"start":33,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":21,"pickleLine":35,"tags":["@calendar","@functional","@scheduledMeeting"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":36,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":23,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When the user clicks \"Schedule Meeting\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Schedule Meeting\"","children":[{"start":17,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"Then User should see the \"Schedule Meeting\" component.","stepMatchArguments":[{"group":{"start":20,"value":"\"Schedule Meeting\"","children":[{"start":21,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":29,"pickleLine":54,"tags":["@calendar","@negative","@scheduledMeetingnegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":47,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Meeting\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Meeting\"","children":[{"start":20,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Subject\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Subject\"","children":[{"start":21,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"Save\"","children":[{"start":54,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Subject\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Subject\"","children":[{"start":35,"value":"Missing required field: Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"And the meeting is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":36,"pickleLine":55,"tags":["@calendar","@negative","@scheduledMeetingnegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":47,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Meeting\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Meeting\"","children":[{"start":20,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Start Date\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Start Date\"","children":[{"start":21,"value":"Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"Save\"","children":[{"start":57,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Start Date\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Start Date\"","children":[{"start":35,"value":"Missing required field: Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":40,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"And the meeting is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":43,"pickleLine":56,"tags":["@calendar","@negative","@scheduledMeetingnegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":47,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Meeting\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Meeting\"","children":[{"start":20,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"When the user leaves the \"End Date\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"End Date\"","children":[{"start":21,"value":"End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"Save\"","children":[{"start":55,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: End Date\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: End Date\"","children":[{"start":35,"value":"Missing required field: End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":47,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"And the meeting is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":52,"pickleLine":59,"tags":["@calendar","@functional","@scheduledCall"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":60,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":61,"keywordType":"Action","textWithKeyword":"When the user clicks \"Schedule Call\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Schedule Call\"","children":[{"start":17,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"Then the \"Schedule Call\" form is displayed with components","stepMatchArguments":[{"group":{"start":4,"value":"\"Schedule Call\"","children":[{"start":5,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":60,"pickleLine":77,"tags":["@calendar","@negative","@scheduledCallNegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Call\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Call\"","children":[{"start":20,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Subject\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Subject\"","children":[{"start":21,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"Save\"","children":[{"start":54,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":63,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Subject\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Subject\"","children":[{"start":35,"value":"Missing required field: Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"And the meeting is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":67,"pickleLine":78,"tags":["@calendar","@negative","@scheduledCallNegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Call\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Call\"","children":[{"start":20,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Start Date & Time\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Start Date & Time\"","children":[{"start":21,"value":"Start Date & Time","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":63,"value":"\"Save\"","children":[{"start":64,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Start Date\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Start Date\"","children":[{"start":35,"value":"Missing required field: Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"And the meeting is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":74,"pickleLine":79,"tags":["@calendar","@negative","@scheduledCallNegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Schedule Call\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Schedule Call\"","children":[{"start":20,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":76,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Duration\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Duration\"","children":[{"start":21,"value":"Duration","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"Save\"","children":[{"start":55,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":77,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Duration\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Duration\"","children":[{"start":35,"value":"Missing required field: Duration","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"And the meeting is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":83,"pickleLine":84,"tags":["@calendar","@functional","@creatTask"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":84,"gherkinStepLine":85,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":85,"gherkinStepLine":86,"keywordType":"Action","textWithKeyword":"When the user clicks \"Create Task\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Create Task\"","children":[{"start":17,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":86,"gherkinStepLine":87,"keywordType":"Outcome","textWithKeyword":"Then a new \"Create Task\" form is displayed with components","stepMatchArguments":[{"group":{"start":6,"value":"\"Create Task\"","children":[{"start":7,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":91,"pickleLine":102,"tags":["@calendar","@negative","@createTaskNegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":92,"gherkinStepLine":95,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Task\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Task\"","children":[{"start":20,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Subject\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Subject\"","children":[{"start":21,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"Save\"","children":[{"start":54,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":94,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Subject\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Subject\"","children":[{"start":35,"value":"Missing required field: Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":95,"gherkinStepLine":98,"keywordType":"Outcome","textWithKeyword":"And the meeting is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":98,"pickleLine":103,"tags":["@calendar","@negative","@createTaskNegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":99,"gherkinStepLine":95,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Task\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Task\"","children":[{"start":20,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":100,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Priority\" field blank and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Priority\"","children":[{"start":21,"value":"Priority","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"Save\"","children":[{"start":55,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":101,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Priority\"","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Priority\"","children":[{"start":35,"value":"Missing required field: Priority","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":102,"gherkinStepLine":98,"keywordType":"Outcome","textWithKeyword":"And the meeting is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":107,"pickleLine":107,"tags":["@calendar","@functional","@todayView"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":108,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":109,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When the user opens the \"Calendar\" dropdown menu and clicks \"Today\"","stepMatchArguments":[{"group":{"start":19,"value":"\"Calendar\"","children":[{"start":20,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":55,"value":"\"Today\"","children":[{"start":56,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":110,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then the calendar refreshes to display the  current date activities with buttons \"Day\", \"Week\", \"Month\", \"Shared Month\", \"Shared Week\", \"Settings\" and \"Calendar icon\" are displayed","stepMatchArguments":[{"group":{"start":76,"value":"\"Day\"","children":[{"start":77,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":83,"value":"\"Week\"","children":[{"start":84,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":91,"value":"\"Month\"","children":[{"start":92,"value":"Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":100,"value":"\"Shared Month\"","children":[{"start":101,"value":"Shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":116,"value":"\"Shared Week\"","children":[{"start":117,"value":"Shared Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":131,"value":"\"Settings\"","children":[{"start":132,"value":"Settings","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":146,"value":"\"Calendar icon\"","children":[{"start":147,"value":"Calendar icon","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":113,"pickleLine":113,"tags":["@calendar","@functional","@assignedUser"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":114,"gherkinStepLine":114,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Today\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Today\"","children":[{"start":27,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":115,"gherkinStepLine":115,"keywordType":"Action","textWithKeyword":"When the user views the row directly above the day column headers","stepMatchArguments":[]},{"pwStepLine":116,"gherkinStepLine":116,"keywordType":"Outcome","textWithKeyword":"Then the assigned user's name is displayed","stepMatchArguments":[]}]},
  {"pwTestLine":119,"pickleLine":119,"tags":["@calendar","@functional","@createActivityPopup"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":120,"gherkinStepLine":120,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Today\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Today\"","children":[{"start":27,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":121,"gherkinStepLine":121,"keywordType":"Action","textWithKeyword":"When the user click the cell corresponding to a specific time slot in the calendar grid","stepMatchArguments":[]},{"pwStepLine":122,"gherkinStepLine":122,"keywordType":"Outcome","textWithKeyword":"Then a popup window appears with options to create a new activity, including fields for \"Subject\", \"Start Date\", \"End Date\"","stepMatchArguments":[{"group":{"start":83,"value":"\"Subject\"","children":[{"start":84,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":94,"value":"\"Start Date\"","children":[{"start":95,"value":"Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":108,"value":"\"End Date\"","children":[{"start":109,"value":"End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":125,"pickleLine":125,"tags":["@calendar","@functional","@savedActivity"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":126,"gherkinStepLine":126,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Today\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Today\"","children":[{"start":27,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":127,"gherkinStepLine":127,"keywordType":"Action","textWithKeyword":"When the user click the cell corresponding to a specific time slot in the calendar grid","stepMatchArguments":[]},{"pwStepLine":128,"gherkinStepLine":128,"keywordType":"Action","textWithKeyword":"And the user enters a valid value in the \"Subject\", \"Start Date\", \"End Date\"","stepMatchArguments":[{"group":{"start":37,"value":"\"Subject\"","children":[{"start":38,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":48,"value":"\"Start Date\"","children":[{"start":49,"value":"Start Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":62,"value":"\"End Date\"","children":[{"start":63,"value":"End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":129,"gherkinStepLine":129,"keywordType":"Action","textWithKeyword":"And the user clicks the \"Save\" button","stepMatchArguments":[{"group":{"start":20,"value":"\"Save\"","children":[{"start":21,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":130,"gherkinStepLine":130,"keywordType":"Outcome","textWithKeyword":"Then the popup closes","stepMatchArguments":[]},{"pwStepLine":131,"gherkinStepLine":131,"keywordType":"Outcome","textWithKeyword":"And the activity appears in the calendar cell at the corresponding time slot","stepMatchArguments":[]},{"pwStepLine":132,"gherkinStepLine":132,"keywordType":"Outcome","textWithKeyword":"And the cell displays the start time and the assigned user's name","stepMatchArguments":[]},{"pwStepLine":133,"gherkinStepLine":133,"keywordType":"Outcome","textWithKeyword":"And the user deletes the saved activity","stepMatchArguments":[]}]},
]; // bdd-data-end