// Generated from: features/Document.feature
import { test } from "../../fixtures/suite8Fixtures.js";

test.describe('Documents Module - View, Navigate and  Activities', () => {

  test.beforeEach('Background', async ({ Given, And, page }, testInfo) => { if (testInfo.error) return;
    await Given('the user is logged into the SuitCRM', null, { page }); 
    await And('the user navigates to the "Documents" module in the menu', null, { page }); 
  });
  
  test('Verify the "Documents"  Button.', { tag: ['@document', '@functional', '@documentsMenu'] }, async ({ When, Then, page }) => { 
    await When('the user hovers over the "Documents" button in the top navigation bar', null, { page }); 
    await Then('user should see the "Create Document" and "View Documents" options in the dropdown menu', null, { page }); 
  });

  test('Veryfy the Document  items.', { tag: ['@document', '@functional', '@documentItems'] }, async ({ When, Then, page }) => { 
    await When('the user clicks the "Documents" menu item', null, { page }); 
    await Then('the user should be navigated to " Document" Dashboard page and should see the components.', {"dataTable":{"rows":[{"cells":[{"value":"Component"},{"value":"Expected Values"}]},{"cells":[{"value":"Page Title"},{"value":"Documents"}]},{"cells":[{"value":"Buttons"},{"value":"Filter"}]}]}}, { page }); 
  });

  test('Verify "Creat Document" page opens', { tag: ['@document', '@functional', '@createDocument'] }, async ({ Given, When, Then, page }) => { 
    await Given('the user has opened the"Documents" dropdown menu', null, { page }); 
    await When('the user selects "Create Document" from the Documents dropdown', null, { page }); 
    await Then('the "Create Document" page is displayed with the components', {"dataTable":{"rows":[{"cells":[{"value":"component"},{"value":"expected value"}]},{"cells":[{"value":"Page Title"},{"value":"Create"}]},{"cells":[{"value":"Buttons"},{"value":"Save, Cancel"}]},{"cells":[{"value":"Tabs"},{"value":"Overview, Other"}]}]}}, { page }); 
  });

  test.describe('Validate error on saving Create Document Page with a mandatory field left blank', () => {

    test('Example #1', { tag: ['@document', '@negative', '@createDocumentNegative'] }, async ({ Given, When, Then, page }) => { 
      await Given('the user is on the "Create Document" form', null, { page }); 
      await When('the user leaves the document "File" field blank and clicks Save', null, { page }); 
      await Then('a document validation message is displayed "Missing required field: File"', null, { page }); 
    });

    test('Example #2', { tag: ['@document', '@negative', '@createDocumentNegative'] }, async ({ Given, When, Then, page }) => { 
      await Given('the user is on the "Create Document" form', null, { page }); 
      await When('the user leaves the document "Document Name" field blank and clicks Save', null, { page }); 
      await Then('a document validation message is displayed "Missing required field: Document Name"', null, { page }); 
    });

    test('Example #3', { tag: ['@document', '@negative', '@createDocumentNegative'] }, async ({ Given, When, Then, page }) => { 
      await Given('the user is on the "Create Document" form', null, { page }); 
      await When('the user leaves the document "Publish Date" field blank and clicks Save', null, { page }); 
      await Then('a document validation message is displayed "Missing required field: Publish Date"', null, { page }); 
    });

    test('Example #4', { tag: ['@document', '@negative', '@createDocumentNegative'] }, async ({ Given, When, Then, page }) => { 
      await Given('the user is on the "Create Document" form', null, { page }); 
      await When('the user leaves the document "Revision" field blank and clicks Save', null, { page }); 
      await Then('a document validation message is displayed "Missing required field: Revision"', null, { page }); 
    });

  });

  test('Create a document and verify it on the detail page and in the View Documents list', { tag: ['@document', '@functional', '@createAndVerifyDocument'] }, async ({ Given, When, Then, And, page }) => { 
    await Given('the user is on the "Create Document" form', null, { page }); 
    await When('the user uploads a file and enters a document name', null, { page }); 
    await And('the user saves the document', null, { page }); 
    await Then('the document detail page is displayed', null, { page }); 
    await And('the page shows an "Edit" and "Action" button.', null, { page }); 
    await When('the user navigates to the "View Documents" page', null, { page }); 
    await Then('the new document appears as a row in the grid', null, { page }); 
    await And('the row shows the correct document name, file and assigned user', null, { page }); 
  });

  test('Verify "View Document" page opens', { tag: ['@document', '@functional', '@viewDocuments'] }, async ({ Given, When, Then, page }) => { 
    await Given('the user has opened the"Documents" dropdown menu', null, { page }); 
    await When('the user selects "View Documents" from the Documents dropdown', null, { page }); 
    await Then('the View Documents list is displayed with the components', {"dataTable":{"rows":[{"cells":[{"value":"Component"},{"value":"Expected Value"}]},{"cells":[{"value":"Page Title"},{"value":"DOCUMENTS"}]},{"cells":[{"value":"Buttons"},{"value":"Filter"}]},{"cells":[{"value":"Bulk Action"},{"value":"Bulk Action dropdown is displayed"}]},{"cells":[{"value":"Columns"},{"value":"Document Name, File, Category, Sub Category, Revision Date, Expiration Date, User"}]},{"cells":[{"value":"Pagination"},{"value":"First page, Previous page, page count (e.g. 1 - 2 of 2), Next page, Last page controls"}]}]}}, { page }); 
  });

});

// == technical section ==

test.beforeEach('BeforeEach Hooks', ({ $runScenarioHooks, page }) => $runScenarioHooks('before', { page }));
test.afterEach('AfterEach Hooks', ({ $runScenarioHooks, page }) => $runScenarioHooks('after', { page }));

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/Document.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":11,"pickleLine":11,"tags":["@document","@functional","@documentsMenu"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Documents\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Documents\"","children":[{"start":27,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user hovers over the \"Documents\" button in the top navigation bar","stepMatchArguments":[{"group":{"start":25,"value":"\"Documents\"","children":[{"start":26,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then user should see the \"Create Document\" and \"View Documents\" options in the dropdown menu","stepMatchArguments":[{"group":{"start":20,"value":"\"Create Document\"","children":[{"start":21,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":42,"value":"\"View Documents\"","children":[{"start":43,"value":"View Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":16,"pickleLine":16,"tags":["@document","@functional","@documentItems"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Documents\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Documents\"","children":[{"start":27,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":17,"keywordType":"Action","textWithKeyword":"When the user clicks the \"Documents\" menu item","stepMatchArguments":[{"group":{"start":20,"value":"\"Documents\"","children":[{"start":21,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":18,"gherkinStepLine":18,"keywordType":"Outcome","textWithKeyword":"Then the user should be navigated to \" Document\" Dashboard page and should see the components.","stepMatchArguments":[{"group":{"start":32,"value":"\" Document\"","children":[{"start":33,"value":" Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":21,"pickleLine":25,"tags":["@document","@functional","@createDocument"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Documents\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Documents\"","children":[{"start":27,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"Given the user has opened the\"Documents\" dropdown menu","stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":27,"keywordType":"Action","textWithKeyword":"When the user selects \"Create Document\" from the Documents dropdown","stepMatchArguments":[{"group":{"start":17,"value":"\"Create Document\"","children":[{"start":18,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":28,"keywordType":"Outcome","textWithKeyword":"Then the \"Create Document\" page is displayed with the components","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Document\"","children":[{"start":5,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":29,"pickleLine":45,"tags":["@document","@negative","@createDocumentNegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Documents\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Documents\"","children":[{"start":27,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":38,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Document\" form","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Document\"","children":[{"start":20,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"When the user leaves the document \"File\" field blank and clicks Save","stepMatchArguments":[{"group":{"start":29,"value":"\"File\"","children":[{"start":30,"value":"File","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then a document validation message is displayed \"Missing required field: File\"","stepMatchArguments":[{"group":{"start":43,"value":"\"Missing required field: File\"","children":[{"start":44,"value":"Missing required field: File","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":35,"pickleLine":46,"tags":["@document","@negative","@createDocumentNegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Documents\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Documents\"","children":[{"start":27,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":38,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Document\" form","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Document\"","children":[{"start":20,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"When the user leaves the document \"Document Name\" field blank and clicks Save","stepMatchArguments":[{"group":{"start":29,"value":"\"Document Name\"","children":[{"start":30,"value":"Document Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then a document validation message is displayed \"Missing required field: Document Name\"","stepMatchArguments":[{"group":{"start":43,"value":"\"Missing required field: Document Name\"","children":[{"start":44,"value":"Missing required field: Document Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":41,"pickleLine":47,"tags":["@document","@negative","@createDocumentNegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Documents\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Documents\"","children":[{"start":27,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":42,"gherkinStepLine":38,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Document\" form","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Document\"","children":[{"start":20,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"When the user leaves the document \"Publish Date\" field blank and clicks Save","stepMatchArguments":[{"group":{"start":29,"value":"\"Publish Date\"","children":[{"start":30,"value":"Publish Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then a document validation message is displayed \"Missing required field: Publish Date\"","stepMatchArguments":[{"group":{"start":43,"value":"\"Missing required field: Publish Date\"","children":[{"start":44,"value":"Missing required field: Publish Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":47,"pickleLine":48,"tags":["@document","@negative","@createDocumentNegative"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Documents\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Documents\"","children":[{"start":27,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":48,"gherkinStepLine":38,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Document\" form","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Document\"","children":[{"start":20,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"When the user leaves the document \"Revision\" field blank and clicks Save","stepMatchArguments":[{"group":{"start":29,"value":"\"Revision\"","children":[{"start":30,"value":"Revision","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then a document validation message is displayed \"Missing required field: Revision\"","stepMatchArguments":[{"group":{"start":43,"value":"\"Missing required field: Revision\"","children":[{"start":44,"value":"Missing required field: Revision","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":55,"pickleLine":52,"tags":["@document","@functional","@createAndVerifyDocument"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Documents\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Documents\"","children":[{"start":27,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":53,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Document\" form","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Document\"","children":[{"start":20,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":54,"keywordType":"Action","textWithKeyword":"When the user uploads a file and enters a document name","stepMatchArguments":[]},{"pwStepLine":58,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"And the user saves the document","stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then the document detail page is displayed","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":57,"keywordType":"Outcome","textWithKeyword":"And the page shows an \"Edit\" and \"Action\" button.","stepMatchArguments":[{"group":{"start":18,"value":"\"Edit\"","children":[{"start":19,"value":"Edit","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":29,"value":"\"Action\"","children":[{"start":30,"value":"Action","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":59,"keywordType":"Action","textWithKeyword":"When the user navigates to the \"View Documents\" page","stepMatchArguments":[{"group":{"start":26,"value":"\"View Documents\"","children":[{"start":27,"value":"View Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":60,"keywordType":"Outcome","textWithKeyword":"Then the new document appears as a row in the grid","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":61,"keywordType":"Outcome","textWithKeyword":"And the row shows the correct document name, file and assigned user","stepMatchArguments":[]}]},
  {"pwTestLine":66,"pickleLine":64,"tags":["@document","@functional","@viewDocuments"],"steps":[{"pwStepLine":7,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Documents\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Documents\"","children":[{"start":27,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":65,"keywordType":"Context","textWithKeyword":"Given the user has opened the\"Documents\" dropdown menu","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":66,"keywordType":"Action","textWithKeyword":"When the user selects \"View Documents\" from the Documents dropdown","stepMatchArguments":[{"group":{"start":17,"value":"\"View Documents\"","children":[{"start":18,"value":"View Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"Then the View Documents list is displayed with the components","stepMatchArguments":[]}]},
]; // bdd-data-end