// Generated from: features/more/survey.feature
import { test } from "playwright-bdd";

test.describe('Testing Survey feature in SuiteCRM application', () => {

  test.beforeEach('Background', async ({ Given, And }, testInfo) => { if (testInfo.error) return;
    await Given('the user is on any page where the top navigation bar is visible'); 
    await And('the navigation bar contains the "More" menu'); 
    await And('the user has navigated to the "Surveys" Page'); 
  });
  
  test('Survey menu is displayed', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('the user is on the SuiteCRM Dashboard'); 
    await And('the "More" button is visible on the screen'); 
    await When('the user clicks on the "More" button'); 
    await Then('a dropdown menu should be displayed'); 
    await And('the dropdown menu should contain a "Survey" option'); 
  });

  test('Survey menu lists the correct set of sub-options', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('the user has opened the Survey menu from the More button'); 
    await When('the user hovers over the Survey menu options'); 
    await Then('the menu should display the expected sub-options (e.g., "Create Survey", "View Surveys", "Survey Reports")'); 
    await And('each option should be labeled correctly'); 
  });

  test('User navigates to the Survey module by selecting Survey from the More menu', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('the user has opened the Survey menu from the More button'); 
    await When('the user clicks on the "Survey" option'); 
    await Then('the user should be redirected to the Survey module page'); 
    await And('the Survey module should load successfully without errors'); 
  });

  test('Create Survey page loading', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the "Create Survey" page'); 
    await When('the user clicks the "Create Survey" button'); 
    await Then('the Create Survey page will open'); 
  });

  test('Verify mandatory field indicator for Create Survey', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the "Create Survey" page'); 
    await When('the user views the "Name" field'); 
    await Then('a red asterisk (*) is displayed next to "Name" indicating it is a mandatory field'); 
  });

  test('Validate error on saving survey without Name', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the "Create Survey" page and the "Name" field is left blank'); 
    await When('the user clicks the "Save" button'); 
    await Then('a validation message is displayed "Missing required field: Name" and the survey is not saved'); 
  });

  test('Successfully create a survey with mandatory field only - Save', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the "Create Survey" page'); 
    await When('the user enters a valid value in the "Name" field and clicks "Save"'); 
    await Then('the survey is saved successfully and the user is navigated to the survey detail view'); 
  });

  test('Cancel creating a survey with mandatory field filled shows confirmation prompt', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the "Create Survey" page'); 
    await When('the user enters a valid value in the "Name" field and clicks "Cancel"'); 
    await Then('a pop up message appears "Leave site? Changes you made may not be saved." with "Cancel" and "Proceed" buttons'); 
  });

  test('Clear the "Assigned To" field', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the "Assigned To" field contains a user name'); 
    await When('the user clicks the "X" (clear) icon next to "Assigned To"'); 
    await Then('the "Assigned To" field is cleared'); 
  });

  test('Enter text in the "Description" field', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the "Create Survey" page'); 
    await When('the user types text into the "Description" textarea'); 
    await Then('the entered text is retained in the "Description" field'); 
  });

  test('Add multiple questions to a survey', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the "Create Survey" page'); 
    await When('the user clicks "New Question" multiple times and fills in each question\'s details'); 
    await Then('each added question appears as a separate row in the "Questions" table'); 
  });

  test('Delete a question from the survey', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('at least one question has been added to the "Questions" table'); 
    await When('the user clicks the "x" action in the "Actions" column for that question'); 
    await Then('the question is removed from the "Questions" table'); 
  });

  test('Save a fully filled-out survey form', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has entered a valid "Name", updated "Status" and "Description", added one or more questions, and customized "Submit Text", "Satisfied Text", "Neither Text" and "Dissatisfied Text"'); 
    await When('the user clicks the "Save" button'); 
    await Then('the survey is saved with all entered values and the detail page reflects the saved data'); 
  });

  test('User navigates to View Survey from the More menu', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, Then, And }) => { 
    await Given('the user is on the "View Survey" page'); 
    await And('the user clicks the "View Survey" button'); 
    await Then('the user should be redirected to the "Survey" module page'); 
    await And('the page should load successfully without errors'); 
  });

  test('User navigates to Show Survey Responses from the More menu', { tag: ['@more', '@survey', '@functional'] }, async ({ Given, Then, And }) => { 
    await Given('the user is on the "Show Survey Responses" page'); 
    await And('the user clicks the "Show Survey Responses" button'); 
    await Then('the user should be redirected to the "Show Survey Responses" page'); 
    await And('the page should load successfully without errors'); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/more/survey.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":10,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":11,"keywordType":"Context","textWithKeyword":"Given the user is on the SuiteCRM Dashboard","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":12,"keywordType":"Context","textWithKeyword":"And the \"More\" button is visible on the screen","stepMatchArguments":[{"group":{"start":4,"value":"\"More\"","children":[{"start":5,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":15,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"When the user clicks on the \"More\" button","stepMatchArguments":[{"group":{"start":23,"value":"\"More\"","children":[{"start":24,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":16,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then a dropdown menu should be displayed","stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And the dropdown menu should contain a \"Survey\" option","stepMatchArguments":[{"group":{"start":35,"value":"\"Survey\"","children":[{"start":36,"value":"Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":20,"pickleLine":18,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":19,"keywordType":"Context","textWithKeyword":"Given the user has opened the Survey menu from the More button","stepMatchArguments":[]},{"pwStepLine":22,"gherkinStepLine":20,"keywordType":"Action","textWithKeyword":"When the user hovers over the Survey menu options","stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":21,"keywordType":"Outcome","textWithKeyword":"Then the menu should display the expected sub-options (e.g., \"Create Survey\", \"View Surveys\", \"Survey Reports\")","stepMatchArguments":[{"group":{"start":56,"value":"\"Create Survey\"","children":[{"start":57,"value":"Create Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":73,"value":"\"View Surveys\"","children":[{"start":74,"value":"View Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":89,"value":"\"Survey Reports\"","children":[{"start":90,"value":"Survey Reports","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":24,"gherkinStepLine":22,"keywordType":"Outcome","textWithKeyword":"And each option should be labeled correctly","stepMatchArguments":[]}]},
  {"pwTestLine":27,"pickleLine":25,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"Given the user has opened the Survey menu from the More button","stepMatchArguments":[]},{"pwStepLine":29,"gherkinStepLine":27,"keywordType":"Action","textWithKeyword":"When the user clicks on the \"Survey\" option","stepMatchArguments":[{"group":{"start":23,"value":"\"Survey\"","children":[{"start":24,"value":"Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":28,"keywordType":"Outcome","textWithKeyword":"Then the user should be redirected to the Survey module page","stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"And the Survey module should load successfully without errors","stepMatchArguments":[]}]},
  {"pwTestLine":34,"pickleLine":32,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":35,"gherkinStepLine":33,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Survey\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Survey\"","children":[{"start":20,"value":"Create Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When the user clicks the \"Create Survey\" button","stepMatchArguments":[{"group":{"start":20,"value":"\"Create Survey\"","children":[{"start":21,"value":"Create Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then the Create Survey page will open","stepMatchArguments":[]}]},
  {"pwTestLine":40,"pickleLine":38,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":41,"gherkinStepLine":39,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Survey\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Survey\"","children":[{"start":20,"value":"Create Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":42,"gherkinStepLine":40,"keywordType":"Action","textWithKeyword":"When the user views the \"Name\" field","stepMatchArguments":[{"group":{"start":19,"value":"\"Name\"","children":[{"start":20,"value":"Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":41,"keywordType":"Outcome","textWithKeyword":"Then a red asterisk (*) is displayed next to \"Name\" indicating it is a mandatory field","stepMatchArguments":[{"group":{"start":40,"value":"\"Name\"","children":[{"start":41,"value":"Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":46,"pickleLine":44,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":47,"gherkinStepLine":45,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Survey\" page and the \"Name\" field is left blank","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Survey\"","children":[{"start":20,"value":"Create Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":48,"value":"\"Name\"","children":[{"start":49,"value":"Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":48,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"When the user clicks the \"Save\" button","stepMatchArguments":[{"group":{"start":20,"value":"\"Save\"","children":[{"start":21,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"Then a validation message is displayed \"Missing required field: Name\" and the survey is not saved","stepMatchArguments":[{"group":{"start":34,"value":"\"Missing required field: Name\"","children":[{"start":35,"value":"Missing required field: Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":52,"pickleLine":50,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":51,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Survey\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Survey\"","children":[{"start":20,"value":"Create Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":52,"keywordType":"Action","textWithKeyword":"When the user enters a valid value in the \"Name\" field and clicks \"Save\"","stepMatchArguments":[{"group":{"start":37,"value":"\"Name\"","children":[{"start":38,"value":"Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":61,"value":"\"Save\"","children":[{"start":62,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":53,"keywordType":"Outcome","textWithKeyword":"Then the survey is saved successfully and the user is navigated to the survey detail view","stepMatchArguments":[]}]},
  {"pwTestLine":58,"pickleLine":56,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":59,"gherkinStepLine":57,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Survey\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Survey\"","children":[{"start":20,"value":"Create Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":60,"gherkinStepLine":58,"keywordType":"Action","textWithKeyword":"When the user enters a valid value in the \"Name\" field and clicks \"Cancel\"","stepMatchArguments":[{"group":{"start":37,"value":"\"Name\"","children":[{"start":38,"value":"Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":61,"value":"\"Cancel\"","children":[{"start":62,"value":"Cancel","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":59,"keywordType":"Outcome","textWithKeyword":"Then a pop up message appears \"Leave site? Changes you made may not be saved.\" with \"Cancel\" and \"Proceed\" buttons","stepMatchArguments":[{"group":{"start":25,"value":"\"Leave site? Changes you made may not be saved.\"","children":[{"start":26,"value":"Leave site? Changes you made may not be saved.","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":79,"value":"\"Cancel\"","children":[{"start":80,"value":"Cancel","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":92,"value":"\"Proceed\"","children":[{"start":93,"value":"Proceed","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":64,"pickleLine":62,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":63,"keywordType":"Context","textWithKeyword":"Given the \"Assigned To\" field contains a user name","stepMatchArguments":[{"group":{"start":4,"value":"\"Assigned To\"","children":[{"start":5,"value":"Assigned To","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":66,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When the user clicks the \"X\" (clear) icon next to \"Assigned To\"","stepMatchArguments":[{"group":{"start":20,"value":"\"X\"","children":[{"start":21,"value":"X","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"Assigned To\"","children":[{"start":46,"value":"Assigned To","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then the \"Assigned To\" field is cleared","stepMatchArguments":[{"group":{"start":4,"value":"\"Assigned To\"","children":[{"start":5,"value":"Assigned To","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":70,"pickleLine":68,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":69,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Survey\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Survey\"","children":[{"start":20,"value":"Create Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":70,"keywordType":"Action","textWithKeyword":"When the user types text into the \"Description\" textarea","stepMatchArguments":[{"group":{"start":29,"value":"\"Description\"","children":[{"start":30,"value":"Description","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":71,"keywordType":"Outcome","textWithKeyword":"Then the entered text is retained in the \"Description\" field","stepMatchArguments":[{"group":{"start":36,"value":"\"Description\"","children":[{"start":37,"value":"Description","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":76,"pickleLine":74,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":77,"gherkinStepLine":75,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Create Survey\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Survey\"","children":[{"start":20,"value":"Create Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":76,"keywordType":"Action","textWithKeyword":"When the user clicks \"New Question\" multiple times and fills in each question's details","stepMatchArguments":[{"group":{"start":16,"value":"\"New Question\"","children":[{"start":17,"value":"New Question","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":79,"gherkinStepLine":77,"keywordType":"Outcome","textWithKeyword":"Then each added question appears as a separate row in the \"Questions\" table","stepMatchArguments":[{"group":{"start":53,"value":"\"Questions\"","children":[{"start":54,"value":"Questions","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":82,"pickleLine":80,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":83,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given at least one question has been added to the \"Questions\" table","stepMatchArguments":[{"group":{"start":44,"value":"\"Questions\"","children":[{"start":45,"value":"Questions","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":84,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When the user clicks the \"x\" action in the \"Actions\" column for that question","stepMatchArguments":[{"group":{"start":20,"value":"\"x\"","children":[{"start":21,"value":"x","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":38,"value":"\"Actions\"","children":[{"start":39,"value":"Actions","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":85,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then the question is removed from the \"Questions\" table","stepMatchArguments":[{"group":{"start":33,"value":"\"Questions\"","children":[{"start":34,"value":"Questions","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":88,"pickleLine":86,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":89,"gherkinStepLine":87,"keywordType":"Context","textWithKeyword":"Given the user has entered a valid \"Name\", updated \"Status\" and \"Description\", added one or more questions, and customized \"Submit Text\", \"Satisfied Text\", \"Neither Text\" and \"Dissatisfied Text\"","stepMatchArguments":[{"group":{"start":29,"value":"\"Name\"","children":[{"start":30,"value":"Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"Status\"","children":[{"start":46,"value":"Status","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":58,"value":"\"Description\"","children":[{"start":59,"value":"Description","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":117,"value":"\"Submit Text\"","children":[{"start":118,"value":"Submit Text","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":132,"value":"\"Satisfied Text\"","children":[{"start":133,"value":"Satisfied Text","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":150,"value":"\"Neither Text\"","children":[{"start":151,"value":"Neither Text","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":169,"value":"\"Dissatisfied Text\"","children":[{"start":170,"value":"Dissatisfied Text","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":90,"gherkinStepLine":88,"keywordType":"Action","textWithKeyword":"When the user clicks the \"Save\" button","stepMatchArguments":[{"group":{"start":20,"value":"\"Save\"","children":[{"start":21,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":91,"gherkinStepLine":89,"keywordType":"Outcome","textWithKeyword":"Then the survey is saved with all entered values and the detail page reflects the saved data","stepMatchArguments":[]}]},
  {"pwTestLine":94,"pickleLine":92,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":95,"gherkinStepLine":93,"keywordType":"Context","textWithKeyword":"Given the user is on the \"View Survey\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"View Survey\"","children":[{"start":20,"value":"View Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":96,"gherkinStepLine":94,"keywordType":"Context","textWithKeyword":"And the user clicks the \"View Survey\" button","stepMatchArguments":[{"group":{"start":20,"value":"\"View Survey\"","children":[{"start":21,"value":"View Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":97,"gherkinStepLine":98,"keywordType":"Outcome","textWithKeyword":"Then the user should be redirected to the \"Survey\" module page","stepMatchArguments":[{"group":{"start":37,"value":"\"Survey\"","children":[{"start":38,"value":"Survey","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":98,"gherkinStepLine":99,"keywordType":"Outcome","textWithKeyword":"And the page should load successfully without errors","stepMatchArguments":[]}]},
  {"pwTestLine":101,"pickleLine":102,"tags":["@more","@survey","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is on any page where the top navigation bar is visible","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the navigation bar contains the \"More\" menu","isBg":true,"stepMatchArguments":[{"group":{"start":32,"value":"\"More\"","children":[{"start":33,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user has navigated to the \"Surveys\" Page","isBg":true,"stepMatchArguments":[{"group":{"start":30,"value":"\"Surveys\"","children":[{"start":31,"value":"Surveys","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":102,"gherkinStepLine":103,"keywordType":"Context","textWithKeyword":"Given the user is on the \"Show Survey Responses\" page","stepMatchArguments":[{"group":{"start":19,"value":"\"Show Survey Responses\"","children":[{"start":20,"value":"Show Survey Responses","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":103,"gherkinStepLine":104,"keywordType":"Context","textWithKeyword":"And the user clicks the \"Show Survey Responses\" button","stepMatchArguments":[{"group":{"start":20,"value":"\"Show Survey Responses\"","children":[{"start":21,"value":"Show Survey Responses","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":104,"gherkinStepLine":105,"keywordType":"Outcome","textWithKeyword":"Then the user should be redirected to the \"Show Survey Responses\" page","stepMatchArguments":[{"group":{"start":37,"value":"\"Show Survey Responses\"","children":[{"start":38,"value":"Show Survey Responses","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":105,"gherkinStepLine":106,"keywordType":"Outcome","textWithKeyword":"And the page should load successfully without errors","stepMatchArguments":[]}]},
]; // bdd-data-end