// Generated from: features\calendar\ dropdownMenuNavigation.feature
import { test } from "playwright-bdd";

test.describe('Calendar Module - View, Navigate and Create Activities', () => {

  test.beforeEach('Background', async ({ Given, And }, testInfo) => { if (testInfo.error) return;
    await Given('the user is logged into the SuitCRM'); 
    await And('the user navigates to the "Calendar" module in the menu'); 
    await And('the calendar loads in "Week" view'); 
  });
  
  test('Verify the Calendar top navigation menu is displayed', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('the user views the top navigation bar'); 
    await Then('the menu items "Calendar", "Accounts", "Contacts", "Opportunities", "Leads", "Quotes", "Documents" and "More" are displayed'); 
  });

  test('Verify the Calendar dropdown menu options are displayed', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('the user clicks the "Calendar" dropdown in the top navigation bar'); 
    await Then('a dropdown appears with options "Schedule Meeting", "Schedule Call", "Create Task" and "Today"'); 
  });

  test('Verify selecting Schedule Meeting opens the meeting creation form', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has opened the "Calendar" dropdown menu'); 
    await When('the user clicks "Schedule Meeting"'); 
    await Then('a new "Schedule Meeting" form is displayed for the user to fill in'); 
  });

  test('Verify selecting Schedule Call opens the call creation form', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has opened the "Calendar" dropdown menu'); 
    await When('the user clicks "Schedule Call"'); 
    await Then('a new "Schedule Call" form is displayed for the user to fill in'); 
  });

  test('Verify selecting Create Task opens the task creation form', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has opened the "Calendar" dropdown menu'); 
    await When('the user clicks "Create Task"'); 
    await Then('a new "Create Task" form is displayed for the user to fill in'); 
  });

  test('Verify selecting Today returns the calendar to the current date', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has opened the "Calendar" dropdown menu'); 
    await When('the user opens the "Calendar" dropdown menu and clicks "Today"'); 
    await Then('the calendar refreshes to display the  current date activities'); 
  });

  test('Verify the view toggle buttons are displayed', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('the user views the row below the page title Calender'); 
    await Then('the buttons "Day", "Month", "Shared Month" ,"Shared Week" ,"Calender icon" and  "Calender Settings"are displayed'); 
  });

  test('Verify the calendar header shows the correct week date range', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Week" view'); 
    await When('the user views the grey header bar above the day columns'); 
    await Then('the header displays current weeks ,start date and end date'); 
  });

  test('Verify all seven days of the week are displayed as columns', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Week" view'); 
    await When('the user views the calendar grid'); 
    await Then('seven day columns are displayed labeled "Sunday  throght Saturday along with date"'); 
  });

  test('Verify the assigned user name is displayed above the calendar grid', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Week" view'); 
    await When('the user views the row directly above the day column headers'); 
    await Then('the assigned user\'s name is displayed'); 
  });

  test('Verify the current day column is highlighted', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Week" view and today\'s date falls within the displayed week'); 
    await When('the user views the day columns'); 
    await Then('the column for "Currnet day" is highlighted with a distinct background color .'); 
  });

  test('Verify hourly time slots are displayed for each day', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Week" view'); 
    await When('the user views the left-hand time axis and the grid rows'); 
    await Then('hourly rows from "start tim eto end time" are displayed and aligned across all seven day columns'); 
  });

  test('Verify navigating to the previous week using the back arrow', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is displaying the chosen week'); 
    await When('the user clicks the left navigation arrow "<" in the header bar'); 
    await Then('the calendar updates to display the preceding week.'); 
  });

  test('Verify navigating to the next week using the forward arrow', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is displaying the chosen week'); 
    await When('the user clicks the right navigation arrow ">" in the header bar'); 
    await Then('the calendar updates to display the next week.'); 
  });

  test('Verify the Settings button is accessible from the Calendar page', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('the user clicks the "SETTINGS" button in the top-right corner'); 
    await Then('the calendar settings panel or page is displayed'); 
  });

  test('Hover existing calender item', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('user Hovering on the existing cell calender item'); 
    await Then('task will show'); 
  });

  test('Verify the calendar grid loads within an acceptable time (Performance)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the user navigates to the Calendar module'); 
    await When('the calendar page is requested'); 
    await Then('the full week grid, including all day columns and hourly rows, renders within 2 to 5 seconds'); 
  });

  test('Verify the current-day highlight is visually distinguishable (Usability)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Week" view'); 
    await When('the user views the day column headers'); 
    await Then('the current day column uses a color with sufficient contrast against adjacent columns to be identifiable at a glance'); 
  });

  test('Verify the calendar layout adapts to different screen resolutions (Responsiveness)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Week" view'); 
    await When('the browser window is resized between desktop, tablet and mobile breakpoints'); 
    await Then('the day columns, time axis and header remain legible and correctly aligned without horizontal content loss'); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features\\calendar\\ dropdownMenuNavigation.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":10,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":11,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user views the top navigation bar","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the menu items \"Calendar\", \"Accounts\", \"Contacts\", \"Opportunities\", \"Leads\", \"Quotes\", \"Documents\" and \"More\" are displayed","stepMatchArguments":[{"group":{"start":15,"value":"\"Calendar\"","children":[{"start":16,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":27,"value":"\"Accounts\"","children":[{"start":28,"value":"Accounts","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":39,"value":"\"Contacts\"","children":[{"start":40,"value":"Contacts","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"Opportunities\"","children":[{"start":52,"value":"Opportunities","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":68,"value":"\"Leads\"","children":[{"start":69,"value":"Leads","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":77,"value":"\"Quotes\"","children":[{"start":78,"value":"Quotes","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":87,"value":"\"Documents\"","children":[{"start":88,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":103,"value":"\"More\"","children":[{"start":104,"value":"More","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":18,"pickleLine":16,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":19,"gherkinStepLine":17,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":18,"keywordType":"Action","textWithKeyword":"When the user clicks the \"Calendar\" dropdown in the top navigation bar","stepMatchArguments":[{"group":{"start":20,"value":"\"Calendar\"","children":[{"start":21,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then a dropdown appears with options \"Schedule Meeting\", \"Schedule Call\", \"Create Task\" and \"Today\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Schedule Meeting\"","children":[{"start":33,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":52,"value":"\"Schedule Call\"","children":[{"start":53,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":69,"value":"\"Create Task\"","children":[{"start":70,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":87,"value":"\"Today\"","children":[{"start":88,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":24,"pickleLine":22,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":26,"gherkinStepLine":24,"keywordType":"Action","textWithKeyword":"When the user clicks \"Schedule Meeting\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Schedule Meeting\"","children":[{"start":17,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":25,"keywordType":"Outcome","textWithKeyword":"Then a new \"Schedule Meeting\" form is displayed for the user to fill in","stepMatchArguments":[{"group":{"start":6,"value":"\"Schedule Meeting\"","children":[{"start":7,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":30,"pickleLine":28,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When the user clicks \"Schedule Call\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Schedule Call\"","children":[{"start":17,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":31,"keywordType":"Outcome","textWithKeyword":"Then a new \"Schedule Call\" form is displayed for the user to fill in","stepMatchArguments":[{"group":{"start":6,"value":"\"Schedule Call\"","children":[{"start":7,"value":"Schedule Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":36,"pickleLine":34,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":35,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":36,"keywordType":"Action","textWithKeyword":"When the user clicks \"Create Task\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Create Task\"","children":[{"start":17,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":37,"keywordType":"Outcome","textWithKeyword":"Then a new \"Create Task\" form is displayed for the user to fill in","stepMatchArguments":[{"group":{"start":6,"value":"\"Create Task\"","children":[{"start":7,"value":"Create Task","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":42,"pickleLine":40,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given the user has opened the \"Calendar\" dropdown menu","stepMatchArguments":[{"group":{"start":24,"value":"\"Calendar\"","children":[{"start":25,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":42,"keywordType":"Action","textWithKeyword":"When the user opens the \"Calendar\" dropdown menu and clicks \"Today\"","stepMatchArguments":[{"group":{"start":19,"value":"\"Calendar\"","children":[{"start":20,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":55,"value":"\"Today\"","children":[{"start":56,"value":"Today","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":43,"keywordType":"Outcome","textWithKeyword":"Then the calendar refreshes to display the  current date activities","stepMatchArguments":[]}]},
  {"pwTestLine":48,"pickleLine":46,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":47,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"When the user views the row below the page title Calender","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":49,"keywordType":"Outcome","textWithKeyword":"Then the buttons \"Day\", \"Month\", \"Shared Month\" ,\"Shared Week\" ,\"Calender icon\" and  \"Calender Settings\"are displayed","stepMatchArguments":[{"group":{"start":12,"value":"\"Day\"","children":[{"start":13,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":19,"value":"\"Month\"","children":[{"start":20,"value":"Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"Shared Month\"","children":[{"start":29,"value":"Shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"Shared Week\"","children":[{"start":45,"value":"Shared Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":59,"value":"\"Calender icon\"","children":[{"start":60,"value":"Calender icon","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":54,"pickleLine":52,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":53,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Week\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Week\"","children":[{"start":27,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":54,"keywordType":"Action","textWithKeyword":"When the user views the grey header bar above the day columns","stepMatchArguments":[]},{"pwStepLine":57,"gherkinStepLine":55,"keywordType":"Outcome","textWithKeyword":"Then the header displays current weeks ,start date and end date","stepMatchArguments":[]}]},
  {"pwTestLine":60,"pickleLine":58,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":59,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Week\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Week\"","children":[{"start":27,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":60,"keywordType":"Action","textWithKeyword":"When the user views the calendar grid","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":61,"keywordType":"Outcome","textWithKeyword":"Then seven day columns are displayed labeled \"Sunday  throght Saturday along with date\"","stepMatchArguments":[{"group":{"start":40,"value":"\"Sunday  throght Saturday along with date\"","children":[{"start":41,"value":"Sunday  throght Saturday along with date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":66,"pickleLine":64,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":65,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Week\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Week\"","children":[{"start":27,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":66,"keywordType":"Action","textWithKeyword":"When the user views the row directly above the day column headers","stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"Then the assigned user's name is displayed","stepMatchArguments":[]}]},
  {"pwTestLine":72,"pickleLine":70,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":71,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Week\" view and today's date falls within the displayed week","stepMatchArguments":[{"group":{"start":26,"value":"\"Week\"","children":[{"start":27,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":74,"gherkinStepLine":72,"keywordType":"Action","textWithKeyword":"When the user views the day columns","stepMatchArguments":[]},{"pwStepLine":75,"gherkinStepLine":73,"keywordType":"Outcome","textWithKeyword":"Then the column for \"Currnet day\" is highlighted with a distinct background color .","stepMatchArguments":[{"group":{"start":15,"value":"\"Currnet day\"","children":[{"start":16,"value":"Currnet day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":78,"pickleLine":76,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":79,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Week\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Week\"","children":[{"start":27,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":80,"gherkinStepLine":78,"keywordType":"Action","textWithKeyword":"When the user views the left-hand time axis and the grid rows","stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":79,"keywordType":"Outcome","textWithKeyword":"Then hourly rows from \"start tim eto end time\" are displayed and aligned across all seven day columns","stepMatchArguments":[{"group":{"start":17,"value":"\"start tim eto end time\"","children":[{"start":18,"value":"start tim eto end time","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":84,"pickleLine":82,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":85,"gherkinStepLine":83,"keywordType":"Context","textWithKeyword":"Given the calendar is displaying the chosen week","stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":84,"keywordType":"Action","textWithKeyword":"When the user clicks the left navigation arrow \"<\" in the header bar","stepMatchArguments":[{"group":{"start":42,"value":"\"<\"","children":[{"start":43,"value":"<","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":85,"keywordType":"Outcome","textWithKeyword":"Then the calendar updates to display the preceding week.","stepMatchArguments":[]}]},
  {"pwTestLine":90,"pickleLine":88,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":91,"gherkinStepLine":89,"keywordType":"Context","textWithKeyword":"Given the calendar is displaying the chosen week","stepMatchArguments":[]},{"pwStepLine":92,"gherkinStepLine":90,"keywordType":"Action","textWithKeyword":"When the user clicks the right navigation arrow \">\" in the header bar","stepMatchArguments":[{"group":{"start":43,"value":"\">\"","children":[{"start":44,"value":">","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":91,"keywordType":"Outcome","textWithKeyword":"Then the calendar updates to display the next week.","stepMatchArguments":[]}]},
  {"pwTestLine":96,"pickleLine":94,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":97,"gherkinStepLine":95,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":98,"gherkinStepLine":96,"keywordType":"Action","textWithKeyword":"When the user clicks the \"SETTINGS\" button in the top-right corner","stepMatchArguments":[{"group":{"start":20,"value":"\"SETTINGS\"","children":[{"start":21,"value":"SETTINGS","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":99,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"Then the calendar settings panel or page is displayed","stepMatchArguments":[]}]},
  {"pwTestLine":102,"pickleLine":100,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":103,"gherkinStepLine":101,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":104,"gherkinStepLine":102,"keywordType":"Action","textWithKeyword":"When user Hovering on the existing cell calender item","stepMatchArguments":[]},{"pwStepLine":105,"gherkinStepLine":103,"keywordType":"Outcome","textWithKeyword":"Then task will show","stepMatchArguments":[]}]},
  {"pwTestLine":108,"pickleLine":106,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":109,"gherkinStepLine":107,"keywordType":"Context","textWithKeyword":"Given the user navigates to the Calendar module","stepMatchArguments":[]},{"pwStepLine":110,"gherkinStepLine":108,"keywordType":"Action","textWithKeyword":"When the calendar page is requested","stepMatchArguments":[]},{"pwStepLine":111,"gherkinStepLine":109,"keywordType":"Outcome","textWithKeyword":"Then the full week grid, including all day columns and hourly rows, renders within 2 to 5 seconds","stepMatchArguments":[{"group":{"start":78,"value":"2"},"parameterTypeName":"int"},{"group":{"start":83,"value":"5"},"parameterTypeName":"int"}]}]},
  {"pwTestLine":114,"pickleLine":112,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":115,"gherkinStepLine":113,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Week\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Week\"","children":[{"start":27,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":116,"gherkinStepLine":114,"keywordType":"Action","textWithKeyword":"When the user views the day column headers","stepMatchArguments":[]},{"pwStepLine":117,"gherkinStepLine":115,"keywordType":"Outcome","textWithKeyword":"Then the current day column uses a color with sufficient contrast against adjacent columns to be identifiable at a glance","stepMatchArguments":[]}]},
  {"pwTestLine":120,"pickleLine":118,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Week\"","children":[{"start":23,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":121,"gherkinStepLine":119,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Week\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Week\"","children":[{"start":27,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":122,"gherkinStepLine":120,"keywordType":"Action","textWithKeyword":"When the browser window is resized between desktop, tablet and mobile breakpoints","stepMatchArguments":[]},{"pwStepLine":123,"gherkinStepLine":121,"keywordType":"Outcome","textWithKeyword":"Then the day columns, time axis and header remain legible and correctly aligned without horizontal content loss","stepMatchArguments":[]}]},
]; // bdd-data-end