// Generated from: features/calendar/createActivityPopup.feature
import { test } from "playwright-bdd";

test.describe('Create New  Activity Popup - Schedule Meeting / Log Call', () => {

  test.beforeEach('Background', async ({ Given, And }, testInfo) => { if (testInfo.error) return;
    await Given('the user is logged into the CRM'); 
    await And('the user is on the Calendar page in "Week" view'); 
    await And('the user clicks on empty cell in the calendar grid'); 
    await And('the "Create Activity" popup is displayed'); 
  });
  
  test('Verify the Create Activity popup opens with Schedule Meeting selected by default', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Week" view'); 
    await When('the user clicks an available hour cell in the calendar grid'); 
    await Then('the "Schedule Meeting" radio option is selected by default and the "Log Call" option is unselected'); 
  });

  test('Verify switching to Log Call updates the form', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open with "Schedule Meeting" selected'); 
    await When('the user clicks an available hour cell in the calendar grid &When the user selects the "Log Call" radio option'); 
    await Then('the form fields update to reflect the "Log Call" activity type'); 
  });

  test('Verify the Start Date defaults to the date/time of the clicked calendar cell', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open with "Schedule Meeting" selected'); 
    await When('the user clicks the cell for "current day" in the calendar grid'); 
    await Then('the "START DATE" field is pre-populated with based on selected date.'); 
  });

  test('Verify Start Date is a mandatory field', { tag: ['@calendar'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open with "Schedule Meeting" selected'); 
    await When('the user leaves the "Start date" field empty and clicks "Save"'); 
    await Then('a validation error is displayed "Missing required field: Subject"'); 
  });

  test('Verify Subject is a mandatory field', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open with "Schedule Meeting" selected'); 
    await When('the user leaves the "SUBJECT" field empty and clicks "Save"'); 
    await Then('a validation error is displayed indicating "Subject" is required and the activity is not saved'); 
  });

  test('Verify End date is a mandatory field', { tag: ['@calendar'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open with "Schedule Meeting" selected'); 
    await When('the user leaves the "End date" field empty and clicks "Save"'); 
    await Then('a validation error is displayed "Missing required field: End Date"'); 
  });

  test('Verify reminder action', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open with "Schedule Meeting" selected'); 
    await When('the user clicks the red "X" icon next to the "Popup" action only'); 
    await Then('the "Popup" reminder action is removed from the list'); 
  });

  test('Verify reminder action', { tag: ['@calendar'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open with "Schedule Meeting" selected'); 
    await When('the user clicks the red "X" icon next to the "Email invitees" action only'); 
    await Then('the validation error displayed"Then the "Popup" reminder action is removed from the list"'); 
  });

  test('Verify reminder action', { tag: ['@calendar'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open with "Schedule Meeting" selected'); 
    await When('the user clicks the red "X" icon both'); 
    await Then('Remainder is not set for either a pop up or email'); 
  });

  test('Verify Add reminder button scenario', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open'); 
    await When('the user clicks the "+ Add reminder" button'); 
    await Then('a new blank reminder action row is added to the "REMINDERS" section'); 
  });

  test('Verify remove reminder button scenario', { tag: ['@calendar'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open'); 
    await When('the user clicks the "- Add reminder" button'); 
    await Then('excisting eminder action row isremove from the "REMINDERS" section'); 
  });

  test('Verify add invitees using search', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has entered required fields and added at least one invitee'); 
    await When('the user enters  any of the invalid  "First Name", "Last Name" or "Email" field under "Add Invitees" and clicks "Search"'); 
    await Then('validation error message display"Sorry, no results were found. Please create an invitee below."'); 
  });

  test('Verify creating a new invitee as a Contact', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user has entered data into the "Create Activity" popup'); 
    await When('the user clicks "As Contact" under "Create an invitee"'); 
    await Then('a new contact creation form is displayed for the user to add as an invitee'); 
  });

  test('Verify Save button creates the activity', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is creating a brand new activity that has not yet been saved'); 
    await When('the user clicks "Save"'); 
    await Then('the activity is created, the popup closes, and the new activity appears on the calendar grid'); 
  });

  test('Verify Save & Send Invites sends email notifications', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open'); 
    await When('the user clicks "Save & Send Invites"'); 
    await Then('the activity is saved and an email invitation is sent to each added invitee'); 
  });

  test('Verify Cancel button discards changes', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open'); 
    await When('the user clicks "Cancel"'); 
    await Then('the popup closes and no activity is created'); 
  });

  test('Verify the close "X" icon discards the popup', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open'); 
    await When('the user clicks the "X" icon in the top-right corner of the popup'); 
    await Then('the popup closes without saving any data'); 
  });

  test('Verify End Date cannot be earlier than Start Date', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the "Create Activity" popup is open'); 
    await When('the user sets an "END DATE" earlier than the "START DATE" and clicks "Save"'); 
    await Then('a validation error is displayed and the activity is not saved'); 
  });

  test('Verify the popup loads within an acceptable time (Performance)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('the user clicks an hour cell in the calendar grid'); 
    await Then('the "Create Activity" popup renders fully within 2 to 5 seconds'); 
  });

  test('Verify mandatory fields are visually distinguishable (Usability)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('the user views the "SUBJECT", "START DATE" and "END DATE" labels'); 
    await Then('each mandatory field label is marked with a red asterisk "*" to distinguish it from optional fields'); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/calendar/createActivityPopup.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":13,"pickleLine":11,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":12,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Week\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Week\"","children":[{"start":27,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":15,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"When the user clicks an available hour cell in the calendar grid","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then the \"Schedule Meeting\" radio option is selected by default and the \"Log Call\" option is unselected","stepMatchArguments":[{"group":{"start":4,"value":"\"Schedule Meeting\"","children":[{"start":5,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":67,"value":"\"Log Call\"","children":[{"start":68,"value":"Log Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":19,"pickleLine":17,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":20,"gherkinStepLine":18,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open with \"Schedule Meeting\" selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Schedule Meeting\"","children":[{"start":42,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":19,"keywordType":"Action","textWithKeyword":"When the user clicks an available hour cell in the calendar grid &When the user selects the \"Log Call\" radio option","stepMatchArguments":[{"group":{"start":87,"value":"\"Log Call\"","children":[{"start":88,"value":"Log Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"Then the form fields update to reflect the \"Log Call\" activity type","stepMatchArguments":[{"group":{"start":38,"value":"\"Log Call\"","children":[{"start":39,"value":"Log Call","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":25,"pickleLine":23,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":26,"gherkinStepLine":24,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open with \"Schedule Meeting\" selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Schedule Meeting\"","children":[{"start":42,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":25,"keywordType":"Action","textWithKeyword":"When the user clicks the cell for \"current day\" in the calendar grid","stepMatchArguments":[{"group":{"start":29,"value":"\"current day\"","children":[{"start":30,"value":"current day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":26,"keywordType":"Outcome","textWithKeyword":"Then the \"START DATE\" field is pre-populated with based on selected date.","stepMatchArguments":[{"group":{"start":4,"value":"\"START DATE\"","children":[{"start":5,"value":"START DATE","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":31,"pickleLine":28,"tags":["@calendar"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open with \"Schedule Meeting\" selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Schedule Meeting\"","children":[{"start":42,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When the user leaves the \"Start date\" field empty and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"Start date\"","children":[{"start":21,"value":"Start date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":56,"value":"\"Save\"","children":[{"start":57,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":31,"keywordType":"Outcome","textWithKeyword":"Then a validation error is displayed \"Missing required field: Subject\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Missing required field: Subject\"","children":[{"start":33,"value":"Missing required field: Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":37,"pickleLine":34,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":35,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open with \"Schedule Meeting\" selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Schedule Meeting\"","children":[{"start":42,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":36,"keywordType":"Action","textWithKeyword":"When the user leaves the \"SUBJECT\" field empty and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"SUBJECT\"","children":[{"start":21,"value":"SUBJECT","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":53,"value":"\"Save\"","children":[{"start":54,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":40,"gherkinStepLine":37,"keywordType":"Outcome","textWithKeyword":"Then a validation error is displayed indicating \"Subject\" is required and the activity is not saved","stepMatchArguments":[{"group":{"start":43,"value":"\"Subject\"","children":[{"start":44,"value":"Subject","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":43,"pickleLine":40,"tags":["@calendar"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open with \"Schedule Meeting\" selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Schedule Meeting\"","children":[{"start":42,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":42,"keywordType":"Action","textWithKeyword":"When the user leaves the \"End date\" field empty and clicks \"Save\"","stepMatchArguments":[{"group":{"start":20,"value":"\"End date\"","children":[{"start":21,"value":"End date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":54,"value":"\"Save\"","children":[{"start":55,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":43,"keywordType":"Outcome","textWithKeyword":"Then a validation error is displayed \"Missing required field: End Date\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Missing required field: End Date\"","children":[{"start":33,"value":"Missing required field: End Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":49,"pickleLine":47,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":48,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open with \"Schedule Meeting\" selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Schedule Meeting\"","children":[{"start":42,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":51,"gherkinStepLine":49,"keywordType":"Action","textWithKeyword":"When the user clicks the red \"X\" icon next to the \"Popup\" action only","stepMatchArguments":[{"group":{"start":24,"value":"\"X\"","children":[{"start":25,"value":"X","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"Popup\"","children":[{"start":46,"value":"Popup","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":52,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"Then the \"Popup\" reminder action is removed from the list","stepMatchArguments":[{"group":{"start":4,"value":"\"Popup\"","children":[{"start":5,"value":"Popup","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":55,"pickleLine":52,"tags":["@calendar"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":53,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open with \"Schedule Meeting\" selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Schedule Meeting\"","children":[{"start":42,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":54,"keywordType":"Action","textWithKeyword":"When the user clicks the red \"X\" icon next to the \"Email invitees\" action only","stepMatchArguments":[{"group":{"start":24,"value":"\"X\"","children":[{"start":25,"value":"X","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"Email invitees\"","children":[{"start":46,"value":"Email invitees","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":58,"gherkinStepLine":55,"keywordType":"Outcome","textWithKeyword":"Then the validation error displayed\"Then the \"Popup\" reminder action is removed from the list\"","stepMatchArguments":[{"group":{"start":40,"value":"\"Popup\"","children":[{"start":41,"value":"Popup","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":61,"pickleLine":57,"tags":["@calendar"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":58,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open with \"Schedule Meeting\" selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Schedule Meeting\"","children":[{"start":42,"value":"Schedule Meeting","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":63,"gherkinStepLine":59,"keywordType":"Action","textWithKeyword":"When the user clicks the red \"X\" icon both","stepMatchArguments":[{"group":{"start":24,"value":"\"X\"","children":[{"start":25,"value":"X","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":60,"keywordType":"Outcome","textWithKeyword":"Then Remainder is not set for either a pop up or email","stepMatchArguments":[]}]},
  {"pwTestLine":67,"pickleLine":63,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":64,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":65,"keywordType":"Action","textWithKeyword":"When the user clicks the \"+ Add reminder\" button","stepMatchArguments":[{"group":{"start":20,"value":"\"+ Add reminder\"","children":[{"start":21,"value":"+ Add reminder","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"Then a new blank reminder action row is added to the \"REMINDERS\" section","stepMatchArguments":[{"group":{"start":48,"value":"\"REMINDERS\"","children":[{"start":49,"value":"REMINDERS","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":73,"pickleLine":68,"tags":["@calendar"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":74,"gherkinStepLine":69,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":70,"keywordType":"Action","textWithKeyword":"When the user clicks the \"- Add reminder\" button","stepMatchArguments":[{"group":{"start":20,"value":"\"- Add reminder\"","children":[{"start":21,"value":"- Add reminder","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":76,"gherkinStepLine":71,"keywordType":"Outcome","textWithKeyword":"Then excisting eminder action row isremove from the \"REMINDERS\" section","stepMatchArguments":[{"group":{"start":47,"value":"\"REMINDERS\"","children":[{"start":48,"value":"REMINDERS","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":79,"pickleLine":76,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":80,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"Given the user has entered required fields and added at least one invitee","stepMatchArguments":[]},{"pwStepLine":81,"gherkinStepLine":78,"keywordType":"Action","textWithKeyword":"When the user enters  any of the invalid  \"First Name\", \"Last Name\" or \"Email\" field under \"Add Invitees\" and clicks \"Search\"","stepMatchArguments":[{"group":{"start":37,"value":"\"First Name\"","children":[{"start":38,"value":"First Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":51,"value":"\"Last Name\"","children":[{"start":52,"value":"Last Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":66,"value":"\"Email\"","children":[{"start":67,"value":"Email","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":86,"value":"\"Add Invitees\"","children":[{"start":87,"value":"Add Invitees","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":112,"value":"\"Search\"","children":[{"start":113,"value":"Search","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":79,"keywordType":"Outcome","textWithKeyword":"Then validation error message display\"Sorry, no results were found. Please create an invitee below.\"","stepMatchArguments":[]}]},
  {"pwTestLine":85,"pickleLine":82,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":86,"gherkinStepLine":83,"keywordType":"Context","textWithKeyword":"Given the user has entered data into the \"Create Activity\" popup","stepMatchArguments":[{"group":{"start":35,"value":"\"Create Activity\"","children":[{"start":36,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":84,"keywordType":"Action","textWithKeyword":"When the user clicks \"As Contact\" under \"Create an invitee\"","stepMatchArguments":[{"group":{"start":16,"value":"\"As Contact\"","children":[{"start":17,"value":"As Contact","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":35,"value":"\"Create an invitee\"","children":[{"start":36,"value":"Create an invitee","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":88,"gherkinStepLine":85,"keywordType":"Outcome","textWithKeyword":"Then a new contact creation form is displayed for the user to add as an invitee","stepMatchArguments":[]}]},
  {"pwTestLine":91,"pickleLine":89,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":92,"gherkinStepLine":90,"keywordType":"Context","textWithKeyword":"Given the user is creating a brand new activity that has not yet been saved","stepMatchArguments":[]},{"pwStepLine":93,"gherkinStepLine":91,"keywordType":"Action","textWithKeyword":"When the user clicks \"Save\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Save\"","children":[{"start":17,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":94,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"Then the activity is created, the popup closes, and the new activity appears on the calendar grid","stepMatchArguments":[]}]},
  {"pwTestLine":97,"pickleLine":95,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":98,"gherkinStepLine":96,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":99,"gherkinStepLine":97,"keywordType":"Action","textWithKeyword":"When the user clicks \"Save & Send Invites\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Save & Send Invites\"","children":[{"start":17,"value":"Save & Send Invites","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":100,"gherkinStepLine":98,"keywordType":"Outcome","textWithKeyword":"Then the activity is saved and an email invitation is sent to each added invitee","stepMatchArguments":[]}]},
  {"pwTestLine":103,"pickleLine":101,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":104,"gherkinStepLine":102,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":105,"gherkinStepLine":103,"keywordType":"Action","textWithKeyword":"When the user clicks \"Cancel\"","stepMatchArguments":[{"group":{"start":16,"value":"\"Cancel\"","children":[{"start":17,"value":"Cancel","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":104,"keywordType":"Outcome","textWithKeyword":"Then the popup closes and no activity is created","stepMatchArguments":[]}]},
  {"pwTestLine":109,"pickleLine":107,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":110,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":111,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When the user clicks the \"X\" icon in the top-right corner of the popup","stepMatchArguments":[{"group":{"start":20,"value":"\"X\"","children":[{"start":21,"value":"X","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":112,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then the popup closes without saving any data","stepMatchArguments":[]}]},
  {"pwTestLine":115,"pickleLine":115,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":116,"gherkinStepLine":116,"keywordType":"Context","textWithKeyword":"Given the \"Create Activity\" popup is open","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":117,"gherkinStepLine":117,"keywordType":"Action","textWithKeyword":"When the user sets an \"END DATE\" earlier than the \"START DATE\" and clicks \"Save\"","stepMatchArguments":[{"group":{"start":17,"value":"\"END DATE\"","children":[{"start":18,"value":"END DATE","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":45,"value":"\"START DATE\"","children":[{"start":46,"value":"START DATE","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":69,"value":"\"Save\"","children":[{"start":70,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":118,"gherkinStepLine":118,"keywordType":"Outcome","textWithKeyword":"Then a validation error is displayed and the activity is not saved","stepMatchArguments":[]}]},
  {"pwTestLine":121,"pickleLine":121,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":122,"gherkinStepLine":122,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":123,"gherkinStepLine":123,"keywordType":"Action","textWithKeyword":"When the user clicks an hour cell in the calendar grid","stepMatchArguments":[]},{"pwStepLine":124,"gherkinStepLine":124,"keywordType":"Outcome","textWithKeyword":"Then the \"Create Activity\" popup renders fully within 2 to 5 seconds","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":49,"value":"2"},"parameterTypeName":"int"},{"group":{"start":54,"value":"5"},"parameterTypeName":"int"}]}]},
  {"pwTestLine":127,"pickleLine":127,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the CRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user is on the Calendar page in \"Week\" view","isBg":true,"stepMatchArguments":[{"group":{"start":36,"value":"\"Week\"","children":[{"start":37,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the user clicks on empty cell in the calendar grid","isBg":true,"stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And the \"Create Activity\" popup is displayed","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":128,"gherkinStepLine":128,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":129,"gherkinStepLine":129,"keywordType":"Action","textWithKeyword":"When the user views the \"SUBJECT\", \"START DATE\" and \"END DATE\" labels","stepMatchArguments":[{"group":{"start":19,"value":"\"SUBJECT\"","children":[{"start":20,"value":"SUBJECT","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":30,"value":"\"START DATE\"","children":[{"start":31,"value":"START DATE","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":47,"value":"\"END DATE\"","children":[{"start":48,"value":"END DATE","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":130,"gherkinStepLine":130,"keywordType":"Outcome","textWithKeyword":"Then each mandatory field label is marked with a red asterisk \"*\" to distinguish it from optional fields","stepMatchArguments":[{"group":{"start":57,"value":"\"*\"","children":[{"start":58,"value":"*","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end