// Generated from: features/calendar/dayView.feature
import { test } from "playwright-bdd";

test.describe('Calendar Day View', () => {

  test.beforeEach('Background', async ({ Given, And }, testInfo) => { if (testInfo.error) return;
    await Given('the user is logged into the SuitCRM'); 
    await And('the user navigates to the "Calendar" module in the menu'); 
    await And('the calendar loads in "Day" view'); 
  });
  
  test('Verify the view toggle buttons are displayed', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('the user views the row below the page title Calender'); 
    await Then('the buttons "Day", "Month", "Shared Month" ,"Shared Week" ,"Calender icon" and  "Calender Settings"are displayed'); 
  });

  test('Verify the calendar header shows the correct week date range', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Day" view'); 
    await When('the user views the grey header bar above the day columns'); 
    await Then('the header displays current weeks ,start date and end date'); 
  });

  test('Verify all seven days of the week are displayed as columns', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Day" view'); 
    await When('the user views the calendar grid'); 
    await Then('seven day columns are displayed labeled "Sunday  throght Saturday along with date"'); 
  });

  test('Verify the assigned user name is displayed above the calendar grid', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Day" view'); 
    await When('the user views the row directly above the day column headers'); 
    await Then('the assigned user\'s name is displayed'); 
  });

  test('Verify navigating to the previous Day using the back arrow', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is displaying the chosen day'); 
    await When('the user clicks the left navigation arrow "<" in the header bar'); 
    await Then('the calendar updates to display the preceding day.'); 
  });

  test('Verify navigating to the next Day using the forward arrow', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is displaying the chosen day'); 
    await When('the user clicks the right navigation arrow ">" in the header bar'); 
    await Then('the calendar updates to display the preceding day.'); 
  });

  test('Verify the Settings button is accessible from the Calendar page', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Day" view'); 
    await When('the user clicks the "SETTINGS" button in the top-right corner'); 
    await Then('the calendar settings panel or page is displayed'); 
  });

  test('Create  new Activity Popup - Schedule Meeting / Log Call', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Day" view'); 
    await When('user click the cell'); 
    await Then('the "Create Activity" popup renders fully within 2 to 5 seconds'); 
  });

  test('Existing calender item', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Day" view'); 
    await When('user click the existing calender item'); 
    await Then('existing calender item will show'); 
  });

  test('Verify the popup loads within an acceptable time (Performance)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Day" view'); 
    await When('the user clicks an hour cell in the calendar grid'); 
    await Then('the "Create Activity" popup renders fully within 2  to 5 seconds'); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/calendar/dayView.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":11,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Day\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Day\"","children":[{"start":23,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":12,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"When the user views the row below the page title Calender","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then the buttons \"Day\", \"Month\", \"Shared Month\" ,\"Shared Week\" ,\"Calender icon\" and  \"Calender Settings\"are displayed","stepMatchArguments":[{"group":{"start":12,"value":"\"Day\"","children":[{"start":13,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":19,"value":"\"Month\"","children":[{"start":20,"value":"Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"Shared Month\"","children":[{"start":29,"value":"Shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"Shared Week\"","children":[{"start":45,"value":"Shared Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":59,"value":"\"Calender icon\"","children":[{"start":60,"value":"Calender icon","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":18,"pickleLine":17,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Day\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Day\"","children":[{"start":23,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":19,"gherkinStepLine":18,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Day\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Day\"","children":[{"start":27,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":20,"gherkinStepLine":19,"keywordType":"Action","textWithKeyword":"When the user views the grey header bar above the day columns","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"Then the header displays current weeks ,start date and end date","stepMatchArguments":[]}]},
  {"pwTestLine":24,"pickleLine":23,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Day\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Day\"","children":[{"start":23,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":24,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Day\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Day\"","children":[{"start":27,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":26,"gherkinStepLine":25,"keywordType":"Action","textWithKeyword":"When the user views the calendar grid","stepMatchArguments":[]},{"pwStepLine":27,"gherkinStepLine":26,"keywordType":"Outcome","textWithKeyword":"Then seven day columns are displayed labeled \"Sunday  throght Saturday along with date\"","stepMatchArguments":[{"group":{"start":40,"value":"\"Sunday  throght Saturday along with date\"","children":[{"start":41,"value":"Sunday  throght Saturday along with date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":30,"pickleLine":29,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Day\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Day\"","children":[{"start":23,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":30,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Day\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Day\"","children":[{"start":27,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"When the user views the row directly above the day column headers","stepMatchArguments":[]},{"pwStepLine":33,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then the assigned user's name is displayed","stepMatchArguments":[]}]},
  {"pwTestLine":36,"pickleLine":35,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Day\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Day\"","children":[{"start":23,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":36,"keywordType":"Context","textWithKeyword":"Given the calendar is displaying the chosen day","stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When the user clicks the left navigation arrow \"<\" in the header bar","stepMatchArguments":[{"group":{"start":42,"value":"\"<\"","children":[{"start":43,"value":"<","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"Then the calendar updates to display the preceding day.","stepMatchArguments":[]}]},
  {"pwTestLine":42,"pickleLine":41,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Day\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Day\"","children":[{"start":23,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":42,"keywordType":"Context","textWithKeyword":"Given the calendar is displaying the chosen day","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"When the user clicks the right navigation arrow \">\" in the header bar","stepMatchArguments":[{"group":{"start":43,"value":"\">\"","children":[{"start":44,"value":">","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then the calendar updates to display the preceding day.","stepMatchArguments":[]}]},
  {"pwTestLine":48,"pickleLine":47,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Day\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Day\"","children":[{"start":23,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":48,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Day\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Day\"","children":[{"start":27,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":49,"keywordType":"Action","textWithKeyword":"When the user clicks the \"SETTINGS\" button in the top-right corner","stepMatchArguments":[{"group":{"start":20,"value":"\"SETTINGS\"","children":[{"start":21,"value":"SETTINGS","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":51,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"Then the calendar settings panel or page is displayed","stepMatchArguments":[]}]},
  {"pwTestLine":54,"pickleLine":53,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Day\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Day\"","children":[{"start":23,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":54,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Day\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Day\"","children":[{"start":27,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"When user click the cell","stepMatchArguments":[]},{"pwStepLine":57,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then the \"Create Activity\" popup renders fully within 2 to 5 seconds","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":49,"value":"2"},"parameterTypeName":"int"},{"group":{"start":54,"value":"5"},"parameterTypeName":"int"}]}]},
  {"pwTestLine":60,"pickleLine":59,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Day\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Day\"","children":[{"start":23,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":60,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Day\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Day\"","children":[{"start":27,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":61,"keywordType":"Action","textWithKeyword":"When user click the existing calender item","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"Then existing calender item will show","stepMatchArguments":[]}]},
  {"pwTestLine":66,"pickleLine":65,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And the calendar loads in \"Day\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"Day\"","children":[{"start":23,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":66,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Day\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Day\"","children":[{"start":27,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":67,"keywordType":"Action","textWithKeyword":"When the user clicks an hour cell in the calendar grid","stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":68,"keywordType":"Outcome","textWithKeyword":"Then the \"Create Activity\" popup renders fully within 2  to 5 seconds","stepMatchArguments":[{"group":{"start":4,"value":"\"Create Activity\"","children":[{"start":5,"value":"Create Activity","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":49,"value":"2"},"parameterTypeName":"int"},{"group":{"start":55,"value":"5"},"parameterTypeName":"int"}]}]},
]; // bdd-data-end