// Generated from: features/calendar/monthView.feature
import { test } from "playwright-bdd";

test.describe('Calendar Month View', () => {

  test.beforeEach('Background', async ({ Given, Then, And }, testInfo) => { if (testInfo.error) return;
    await Given('the user is logged into the SuitCRM'); 
    await And('the user navigates to the "Calendar" module and click clander module in the menu'); 
    await Then('the "Calendar" page is displayed .'); 
  });
  
  test('Navigate to Month view from calendar', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('The user is on the calender view'); 
    await When('The user clicks the "Month" view button'); 
    await Then('the "Month" page is displayed'); 
  });

  test('Verify the view toggle buttons are displayed', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('the user views the row below the page title Calender'); 
    await Then('the buttons "Day", "Month", "Shared Month" ,"Shared Week" ,"Calender icon" and  "Calender Settings"are displayed'); 
  });

  test('Verify the assigned user name is displayed above the calendar grid', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "month" view'); 
    await When('the user views the row directly above the day column headers'); 
    await Then('the assigned user\'s name is displayed'); 
  });

  test('Verify navigating to the previous Day using the back arrow', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Week" view'); 
    await When('the user clicks the left navigation arrow "<" in the header bar'); 
    await Then('the calendar updates to display the preceding Month'); 
  });

  test('Verify navigating to the next Day using the forward arrow', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is displaying the chosen day'); 
    await When('the user clicks the right navigation arrow ">" in the header bar'); 
    await Then('the calendar updates to display the preceding Month'); 
  });

  test('verify the calender items "task","call","meeting" and event', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "month" view'); 
    await When('The user clicks the "cell" in the calender'); 
    await Then('calender items will pop up with corresponding given selected setting.'); 
  });

  test('Hover existing calender item', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "Month" view'); 
    await When('user Hovering on the existing cell calender item'); 
    await Then('task will show'); 
  });

  test('Verify the calendar grid loads within an acceptable time (Performance)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the user navigates to "Month View" module'); 
    await When('the calendar page is requested'); 
    await Then('Page should load with in within 2 to 5 second'); 
  });

  test('Verify the current-day highlight is visually distinguishable (Usability)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the user navigates to "Month View" module'); 
    await When('the user views the day column headers'); 
    await Then('the current day column uses a color with sufficient contrast against adjacent columns to be identifiable at a glance'); 
  });

  test('Verify the calendar layout adapts to different screen resolutions (Responsiveness)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the user navigates to "Month View" module'); 
    await When('the browser window is resized between desktop, tablet and mobile breakpoints'); 
    await Then('the day columns, time axis and header remain legible and correctly aligned without horizontal content loss'); 
  });

  test('Cross-browser rendering of the Settings modal', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('The Settings modal is opened in the latest versions of Chrome, Firefox, Edge and Safari'); 
    await When('the modal is displayed in each browser'); 
    await Then('The layout, dropdowns, checkboxes and colour swatches render consistently with no visual defects in any browser'); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/calendar/monthView.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":9,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"Given The user is on the calender view","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"When The user clicks the \"Month\" view button","stepMatchArguments":[{"group":{"start":20,"value":"\"Month\"","children":[{"start":21,"value":"Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":15,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"Then the \"Month\" page is displayed","stepMatchArguments":[{"group":{"start":4,"value":"\"Month\"","children":[{"start":5,"value":"Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":18,"pickleLine":15,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":19,"gherkinStepLine":16,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":17,"keywordType":"Action","textWithKeyword":"When the user views the row below the page title Calender","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":18,"keywordType":"Outcome","textWithKeyword":"Then the buttons \"Day\", \"Month\", \"Shared Month\" ,\"Shared Week\" ,\"Calender icon\" and  \"Calender Settings\"are displayed","stepMatchArguments":[{"group":{"start":12,"value":"\"Day\"","children":[{"start":13,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":19,"value":"\"Month\"","children":[{"start":20,"value":"Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"Shared Month\"","children":[{"start":29,"value":"Shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"Shared Week\"","children":[{"start":45,"value":"Shared Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":59,"value":"\"Calender icon\"","children":[{"start":60,"value":"Calender icon","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":24,"pickleLine":21,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":22,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"month\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"month\"","children":[{"start":27,"value":"month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":26,"gherkinStepLine":23,"keywordType":"Action","textWithKeyword":"When the user views the row directly above the day column headers","stepMatchArguments":[]},{"pwStepLine":27,"gherkinStepLine":24,"keywordType":"Outcome","textWithKeyword":"Then the assigned user's name is displayed","stepMatchArguments":[]}]},
  {"pwTestLine":30,"pickleLine":27,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":28,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Week\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Week\"","children":[{"start":27,"value":"Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"When the user clicks the left navigation arrow \"<\" in the header bar","stepMatchArguments":[{"group":{"start":42,"value":"\"<\"","children":[{"start":43,"value":"<","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then the calendar updates to display the preceding Month","stepMatchArguments":[]}]},
  {"pwTestLine":36,"pickleLine":33,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":34,"keywordType":"Context","textWithKeyword":"Given the calendar is displaying the chosen day","stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":35,"keywordType":"Action","textWithKeyword":"When the user clicks the right navigation arrow \">\" in the header bar","stepMatchArguments":[{"group":{"start":43,"value":"\">\"","children":[{"start":44,"value":">","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":36,"keywordType":"Outcome","textWithKeyword":"Then the calendar updates to display the preceding Month","stepMatchArguments":[]}]},
  {"pwTestLine":42,"pickleLine":39,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":40,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"month\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"month\"","children":[{"start":27,"value":"month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":41,"keywordType":"Action","textWithKeyword":"When The user clicks the \"cell\" in the calender","stepMatchArguments":[{"group":{"start":20,"value":"\"cell\"","children":[{"start":21,"value":"cell","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":42,"keywordType":"Outcome","textWithKeyword":"Then calender items will pop up with corresponding given selected setting.","stepMatchArguments":[]}]},
  {"pwTestLine":48,"pickleLine":45,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":46,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"Month\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"Month\"","children":[{"start":27,"value":"Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":47,"keywordType":"Action","textWithKeyword":"When user Hovering on the existing cell calender item","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":48,"keywordType":"Outcome","textWithKeyword":"Then task will show","stepMatchArguments":[]}]},
  {"pwTestLine":54,"pickleLine":51,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":52,"keywordType":"Context","textWithKeyword":"Given the user navigates to \"Month View\" module","stepMatchArguments":[{"group":{"start":22,"value":"\"Month View\"","children":[{"start":23,"value":"Month View","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"When the calendar page is requested","stepMatchArguments":[]},{"pwStepLine":57,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then Page should load with in within 2 to 5 second","stepMatchArguments":[{"group":{"start":32,"value":"2"},"parameterTypeName":"int"},{"group":{"start":37,"value":"5"},"parameterTypeName":"int"}]}]},
  {"pwTestLine":60,"pickleLine":57,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":58,"keywordType":"Context","textWithKeyword":"Given the user navigates to \"Month View\" module","stepMatchArguments":[{"group":{"start":22,"value":"\"Month View\"","children":[{"start":23,"value":"Month View","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":59,"keywordType":"Action","textWithKeyword":"When the user views the day column headers","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":60,"keywordType":"Outcome","textWithKeyword":"Then the current day column uses a color with sufficient contrast against adjacent columns to be identifiable at a glance","stepMatchArguments":[]}]},
  {"pwTestLine":66,"pickleLine":63,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":64,"keywordType":"Context","textWithKeyword":"Given the user navigates to \"Month View\" module","stepMatchArguments":[{"group":{"start":22,"value":"\"Month View\"","children":[{"start":23,"value":"Month View","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":65,"keywordType":"Action","textWithKeyword":"When the browser window is resized between desktop, tablet and mobile breakpoints","stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"Then the day columns, time axis and header remain legible and correctly aligned without horizontal content loss","stepMatchArguments":[]}]},
  {"pwTestLine":72,"pickleLine":69,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module and click clander module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the \"Calendar\" page is displayed .","isBg":true,"stepMatchArguments":[{"group":{"start":4,"value":"\"Calendar\"","children":[{"start":5,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"Given The Settings modal is opened in the latest versions of Chrome, Firefox, Edge and Safari","stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When the modal is displayed in each browser","stepMatchArguments":[]},{"pwStepLine":75,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then The layout, dropdowns, checkboxes and colour swatches render consistently with no visual defects in any browser","stepMatchArguments":[]}]},
]; // bdd-data-end