// Generated from: features/calendar/sharedMonthView.feature
import { test } from "playwright-bdd";

test.describe('Calendar shared Month View', () => {

  test.beforeEach('Background', async ({ Given, Then, And }, testInfo) => { if (testInfo.error) return;
    await Given('the user is logged into the SuitCRM'); 
    await And('the user navigates to the "Calendar" module in the menu'); 
    await Then('the calendar loads in "shared Month" view'); 
  });
  
  test('Verify the view toggle buttons are displayed', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the user is on the Calendar page'); 
    await When('the user views the row below the page title Calender'); 
    await Then('the buttons "Day", "Month", "Shared Month" ,"Shared Week" ,"Calender icon" and  "Calender Settings"are displayed'); 
  });

  test('Verify the assigned user name is displayed above the calendar grid', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in " shared month" view'); 
    await When('the user views the row directly above the day column headers'); 
    await Then('the assigned user\'s name is displayed'); 
  });

  test('verify the calender items "task","call","meeting" and event', { tag: ['@calendar'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in " shared month" view'); 
    await When('The user clicks the "cell" in the calender'); 
    await Then('calender items will pop up with corresponding given selected setting.'); 
  });

  test('Hover existing calender item', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in " shared month" view'); 
    await When('user Hovering on the existing cell calender item'); 
    await Then('assigned task will show'); 
  });

  test('Open the User list buttons from shared moth view', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "shared Month" view'); 
    await When('user click on the user list button'); 
    await Then('user list window pop up'); 
  });

  test('Open the User list buttons from shared moth view', { tag: ['@calendar', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "shared Month" view'); 
    await When('when user select" users" from drop down window and Apply button'); 
    await Then('window closes and corresponding user name shows in the shared month page'); 
  });

  test('Verify the calendar grid loads within an acceptable time (Performance)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the user navigates to the Calendar module'); 
    await When('the calendar page is requested'); 
    await Then('the  shared month page shoul open within 2 to 5 seconds'); 
  });

  test('Verify the current-day highlight is visually distinguishable (Usability)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "shared Month" view'); 
    await When('the user views the day column'); 
    await Then('the current day column uses a color with sufficient contrast against adjacent columns to be identifiable at a glance'); 
  });

  test('Verify the calendar layout adapts to different screen resolutions (Responsiveness)', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('the calendar is loaded in "shared Month" view'); 
    await When('the browser window is resized between desktop, tablet and mobile breakpoints'); 
    await Then('the day columns, time axis and header remain legible and correctly aligned without horizontal content loss'); 
  });

  test('Cross-browser rendering of the Settings modal', { tag: ['@calendar', '@nonFunctional'] }, async ({ Given, When, Then }) => { 
    await Given('The Settings modal is opened in the latest versions of Chrome, Firefox, Edge and Safari'); 
    await When('the modal is displayed in each browser'); 
    await Then('The layout, dropdowns, checkboxes and colour swatches render consistently with no visual defects in any browser'); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/calendar/sharedMonthView.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":11,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the calendar loads in \"shared Month\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"shared Month\"","children":[{"start":23,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":12,"keywordType":"Context","textWithKeyword":"Given the user is on the Calendar page","stepMatchArguments":[]},{"pwStepLine":14,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"When the user views the row below the page title Calender","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then the buttons \"Day\", \"Month\", \"Shared Month\" ,\"Shared Week\" ,\"Calender icon\" and  \"Calender Settings\"are displayed","stepMatchArguments":[{"group":{"start":12,"value":"\"Day\"","children":[{"start":13,"value":"Day","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":19,"value":"\"Month\"","children":[{"start":20,"value":"Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"Shared Month\"","children":[{"start":29,"value":"Shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"Shared Week\"","children":[{"start":45,"value":"Shared Week","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":59,"value":"\"Calender icon\"","children":[{"start":60,"value":"Calender icon","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":18,"pickleLine":18,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the calendar loads in \"shared Month\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"shared Month\"","children":[{"start":23,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":19,"gherkinStepLine":19,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \" shared month\" view","stepMatchArguments":[{"group":{"start":26,"value":"\" shared month\"","children":[{"start":27,"value":" shared month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":20,"gherkinStepLine":20,"keywordType":"Action","textWithKeyword":"When the user views the row directly above the day column headers","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":21,"keywordType":"Outcome","textWithKeyword":"Then the assigned user's name is displayed","stepMatchArguments":[]}]},
  {"pwTestLine":24,"pickleLine":23,"tags":["@calendar"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the calendar loads in \"shared Month\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"shared Month\"","children":[{"start":23,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":25,"gherkinStepLine":24,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \" shared month\" view","stepMatchArguments":[{"group":{"start":26,"value":"\" shared month\"","children":[{"start":27,"value":" shared month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":26,"gherkinStepLine":25,"keywordType":"Action","textWithKeyword":"When The user clicks the \"cell\" in the calender","stepMatchArguments":[{"group":{"start":20,"value":"\"cell\"","children":[{"start":21,"value":"cell","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":26,"keywordType":"Outcome","textWithKeyword":"Then calender items will pop up with corresponding given selected setting.","stepMatchArguments":[]}]},
  {"pwTestLine":30,"pickleLine":29,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the calendar loads in \"shared Month\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"shared Month\"","children":[{"start":23,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":30,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \" shared month\" view","stepMatchArguments":[{"group":{"start":26,"value":"\" shared month\"","children":[{"start":27,"value":" shared month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":32,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"When user Hovering on the existing cell calender item","stepMatchArguments":[]},{"pwStepLine":33,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then assigned task will show","stepMatchArguments":[]}]},
  {"pwTestLine":36,"pickleLine":35,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the calendar loads in \"shared Month\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"shared Month\"","children":[{"start":23,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":36,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"shared Month\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"shared Month\"","children":[{"start":27,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When user click on the user list button","stepMatchArguments":[]},{"pwStepLine":39,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"Then user list window pop up","stepMatchArguments":[]}]},
  {"pwTestLine":42,"pickleLine":41,"tags":["@calendar","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the calendar loads in \"shared Month\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"shared Month\"","children":[{"start":23,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":42,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"shared Month\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"shared Month\"","children":[{"start":27,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"When when user select\" users\" from drop down window and Apply button","stepMatchArguments":[]},{"pwStepLine":45,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then window closes and corresponding user name shows in the shared month page","stepMatchArguments":[]}]},
  {"pwTestLine":48,"pickleLine":47,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the calendar loads in \"shared Month\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"shared Month\"","children":[{"start":23,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":48,"keywordType":"Context","textWithKeyword":"Given the user navigates to the Calendar module","stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":49,"keywordType":"Action","textWithKeyword":"When the calendar page is requested","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":50,"keywordType":"Outcome","textWithKeyword":"Then the  shared month page shoul open within 2 to 5 seconds","stepMatchArguments":[{"group":{"start":41,"value":"2"},"parameterTypeName":"int"},{"group":{"start":46,"value":"5"},"parameterTypeName":"int"}]}]},
  {"pwTestLine":54,"pickleLine":53,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the calendar loads in \"shared Month\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"shared Month\"","children":[{"start":23,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":54,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"shared Month\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"shared Month\"","children":[{"start":27,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"When the user views the day column","stepMatchArguments":[]},{"pwStepLine":57,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then the current day column uses a color with sufficient contrast against adjacent columns to be identifiable at a glance","stepMatchArguments":[]}]},
  {"pwTestLine":60,"pickleLine":59,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the calendar loads in \"shared Month\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"shared Month\"","children":[{"start":23,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":60,"keywordType":"Context","textWithKeyword":"Given the calendar is loaded in \"shared Month\" view","stepMatchArguments":[{"group":{"start":26,"value":"\"shared Month\"","children":[{"start":27,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":61,"keywordType":"Action","textWithKeyword":"When the browser window is resized between desktop, tablet and mobile breakpoints","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"Then the day columns, time axis and header remain legible and correctly aligned without horizontal content loss","stepMatchArguments":[]}]},
  {"pwTestLine":66,"pickleLine":65,"tags":["@calendar","@nonFunctional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given the user is logged into the SuitCRM","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And the user navigates to the \"Calendar\" module in the menu","isBg":true,"stepMatchArguments":[{"group":{"start":26,"value":"\"Calendar\"","children":[{"start":27,"value":"Calendar","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then the calendar loads in \"shared Month\" view","isBg":true,"stepMatchArguments":[{"group":{"start":22,"value":"\"shared Month\"","children":[{"start":23,"value":"shared Month","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":66,"keywordType":"Context","textWithKeyword":"Given The Settings modal is opened in the latest versions of Chrome, Firefox, Edge and Safari","stepMatchArguments":[]},{"pwStepLine":68,"gherkinStepLine":67,"keywordType":"Action","textWithKeyword":"When the modal is displayed in each browser","stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":68,"keywordType":"Outcome","textWithKeyword":"Then The layout, dropdowns, checkboxes and colour swatches render consistently with no visual defects in any browser","stepMatchArguments":[]}]},
]; // bdd-data-end