// Generated from: features/documents/createDocument.feature
import { test } from "playwright-bdd";

test.describe('Create Document Page Checking', () => {

  test.beforeEach('Background', async ({ Given }, testInfo) => { if (testInfo.error) return;
    await Given('User is on "Create Document "Page'); 
  });
  
  test('Open the "Create Documents" page from the "Document" dropdown', { tag: ['@document', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('The user has hovered over the "Documents" menu'); 
    await When('the user click the "Create Document" from the "Documents"'); 
    await Then('"create Document "page will display with two tabs "overview"and "other".'); 
    await And('"over view"  tab highlighted.'); 
  });

  test('Verify validation error when mandatory fields are left empty', { tag: ['@document', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('User is on "Create Document "Page'); 
    await And('The user is on "Create Document" page\'s  "Over view" tab'); 
    await When('user click "save " button without filling the"Document Name"'); 
    await Then('validation eror should be displayed "Missing required field: Document Name " for the "Document Name" field'); 
  });

  test('Verify validation error when mandatory fields are left empty', { tag: ['@document', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('User is on "Create Document "Page'); 
    await And('The user is on "Create Document" page\'s  "Over view" tab'); 
    await When('user click "save " button without filling the"Published Date"'); 
    await Then('validation eror should be displayed "Missing required field: Published Date " for the "Published Date" field'); 
  });

  test('Verify validation error when mandatory fields are left empty', { tag: ['@document', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('User is on "Create Document "Page'); 
    await And('The user is on "Create Document" page\'s  "Over view" tab'); 
    await When('user click "save " button without filling the"Revision"'); 
    await Then('validation eror should be displayed "Missing required field: Revision " for the "Revision" field'); 
  });

  test('Verify validation error when mandatory fields are left empty', { tag: ['@document', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('User is on "Create Document "Page'); 
    await And('The user is on "Create Document" page\'s  "Over view" tab'); 
    await When('user click "save " button without filling the"File"'); 
    await Then('validation eror should be displayed "Missing required field: File " for the "File" field'); 
  });

  test('Verify document is saved successfully when all mandatory fields are filled', { tag: ['@document', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('User is on "Create Document "Page'); 
    await And('The user is on "Create Document" page\'s  "Over view" tab'); 
    await When('user clicks "save" button with all mandatory field are completed'); 
    await Then('saved page will reload with button n "Edit","Action".'); 
  });

  test('Verify "Edit Document" page is displayed after update the document', { tag: ['@document', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('The user is on the page with "Edit" and "Actions" buttons'); 
    await When('we click "edit "button'); 
    await Then('window refresh and saved page will reload with  buttons "Save", and"Cancel" button'); 
  });

  test('Verify "Edit Document" page is displayed after update the document', { tag: ['@document', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('the user has just saved a document and the Document Detail View is open with saved name with star'); 
    await And('The user is on the page with "Edit" and "Actions" buttons'); 
    await When('click "Action" button'); 
    await Then('The drop down contain"Duplicate", and Delete"option will show'); 
  });

  test('Verify duplicate page is created and listed in the task page', { tag: ['@document', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('The user is on the page with "Edit" and "Actions" buttons'); 
    await When('click "Action" Botton and selected"Duplicate"'); 
    await Then('Duplicate page created and listed in "Creat Document"page will display'); 
  });

  test('Verify multiple duplicates can be created', { tag: ['@document', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('The user is on the page with "Edit" and "Actions" buttons'); 
    await When('user click "duplicate "page multiple time'); 
    await Then('Each duplicated page sholud be created  and listed in  "Task page"'); 
  });

  test('Verify created page can be deleted', { tag: ['@document', '@functional'] }, async ({ Given, When, Then, And }) => { 
    await Given('The user is on the page with "Edit" and "Actions" buttons'); 
    await When('user click "action" and selected "delete" option'); 
    await Then('pop up will show with message"Are you sure want to delete this record?" with "cancel",and "Proceed" button.'); 
    await And('user click "Proceed" button'); 
    await And('created task will delete and message will come" record delet succesfully"'); 
  });

  test('verify  saved Created Document is vissible', { tag: ['@document', '@functional'] }, async ({ Given, When, Then }) => { 
    await Given('The user is on "Create Document" page\'s  "Other" tab'); 
    await When('user click "other" tab'); 
    await Then('save page will reload with botton "Edit","Action".'); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/documents/createDocument.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":10,"pickleLine":8,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given The user has hovered over the \"Documents\" menu","stepMatchArguments":[{"group":{"start":30,"value":"\"Documents\"","children":[{"start":31,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user click the \"Create Document\" from the \"Documents\"","stepMatchArguments":[{"group":{"start":19,"value":"\"Create Document\"","children":[{"start":20,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":46,"value":"\"Documents\"","children":[{"start":47,"value":"Documents","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then \"create Document \"page will display with two tabs \"overview\"and \"other\".","stepMatchArguments":[{"group":{"start":64,"value":"\"other\"","children":[{"start":65,"value":"other","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"And \"over view\"  tab highlighted.","stepMatchArguments":[{"group":{"start":0,"value":"\"over view\"","children":[{"start":1,"value":"over view","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":17,"pickleLine":15,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":16,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","stepMatchArguments":[]},{"pwStepLine":19,"gherkinStepLine":17,"keywordType":"Context","textWithKeyword":"And The user is on \"Create Document\" page's  \"Over view\" tab","stepMatchArguments":[{"group":{"start":15,"value":"\"Create Document\"","children":[{"start":16,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Over view\"","children":[{"start":42,"value":"Over view","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":20,"gherkinStepLine":18,"keywordType":"Action","textWithKeyword":"When user click \"save \" button without filling the\"Document Name\"","stepMatchArguments":[{"group":{"start":11,"value":"\"save \"","children":[{"start":12,"value":"save ","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then validation eror should be displayed \"Missing required field: Document Name \" for the \"Document Name\" field","stepMatchArguments":[{"group":{"start":36,"value":"\"Missing required field: Document Name \"","children":[{"start":37,"value":"Missing required field: Document Name ","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":85,"value":"\"Document Name\"","children":[{"start":86,"value":"Document Name","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":24,"pickleLine":22,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":23,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":24,"keywordType":"Context","textWithKeyword":"And The user is on \"Create Document\" page's  \"Over view\" tab","stepMatchArguments":[{"group":{"start":15,"value":"\"Create Document\"","children":[{"start":16,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Over view\"","children":[{"start":42,"value":"Over view","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":25,"keywordType":"Action","textWithKeyword":"When user click \"save \" button without filling the\"Published Date\"","stepMatchArguments":[{"group":{"start":11,"value":"\"save \"","children":[{"start":12,"value":"save ","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":26,"keywordType":"Outcome","textWithKeyword":"Then validation eror should be displayed \"Missing required field: Published Date \" for the \"Published Date\" field","stepMatchArguments":[{"group":{"start":36,"value":"\"Missing required field: Published Date \"","children":[{"start":37,"value":"Missing required field: Published Date ","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":86,"value":"\"Published Date\"","children":[{"start":87,"value":"Published Date","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":31,"pickleLine":29,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":30,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","stepMatchArguments":[]},{"pwStepLine":33,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"And The user is on \"Create Document\" page's  \"Over view\" tab","stepMatchArguments":[{"group":{"start":15,"value":"\"Create Document\"","children":[{"start":16,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Over view\"","children":[{"start":42,"value":"Over view","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":32,"keywordType":"Action","textWithKeyword":"When user click \"save \" button without filling the\"Revision\"","stepMatchArguments":[{"group":{"start":11,"value":"\"save \"","children":[{"start":12,"value":"save ","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":35,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"Then validation eror should be displayed \"Missing required field: Revision \" for the \"Revision\" field","stepMatchArguments":[{"group":{"start":36,"value":"\"Missing required field: Revision \"","children":[{"start":37,"value":"Missing required field: Revision ","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":80,"value":"\"Revision\"","children":[{"start":81,"value":"Revision","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":38,"pickleLine":36,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":39,"gherkinStepLine":37,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","stepMatchArguments":[]},{"pwStepLine":40,"gherkinStepLine":38,"keywordType":"Context","textWithKeyword":"And The user is on \"Create Document\" page's  \"Over view\" tab","stepMatchArguments":[{"group":{"start":15,"value":"\"Create Document\"","children":[{"start":16,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Over view\"","children":[{"start":42,"value":"Over view","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":41,"gherkinStepLine":39,"keywordType":"Action","textWithKeyword":"When user click \"save \" button without filling the\"File\"","stepMatchArguments":[{"group":{"start":11,"value":"\"save \"","children":[{"start":12,"value":"save ","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":42,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"Then validation eror should be displayed \"Missing required field: File \" for the \"File\" field","stepMatchArguments":[{"group":{"start":36,"value":"\"Missing required field: File \"","children":[{"start":37,"value":"Missing required field: File ","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":76,"value":"\"File\"","children":[{"start":77,"value":"File","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":45,"pickleLine":43,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","stepMatchArguments":[]},{"pwStepLine":47,"gherkinStepLine":45,"keywordType":"Context","textWithKeyword":"And The user is on \"Create Document\" page's  \"Over view\" tab","stepMatchArguments":[{"group":{"start":15,"value":"\"Create Document\"","children":[{"start":16,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Over view\"","children":[{"start":42,"value":"Over view","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":48,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"When user clicks \"save\" button with all mandatory field are completed","stepMatchArguments":[{"group":{"start":12,"value":"\"save\"","children":[{"start":13,"value":"save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"Then saved page will reload with button n \"Edit\",\"Action\".","stepMatchArguments":[{"group":{"start":37,"value":"\"Edit\"","children":[{"start":38,"value":"Edit","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":44,"value":"\"Action\"","children":[{"start":45,"value":"Action","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":52,"pickleLine":51,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":52,"keywordType":"Context","textWithKeyword":"Given The user is on the page with \"Edit\" and \"Actions\" buttons","stepMatchArguments":[{"group":{"start":29,"value":"\"Edit\"","children":[{"start":30,"value":"Edit","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Actions\"","children":[{"start":41,"value":"Actions","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"When we click \"edit \"button","stepMatchArguments":[]},{"pwStepLine":55,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then window refresh and saved page will reload with  buttons \"Save\", and\"Cancel\" button","stepMatchArguments":[{"group":{"start":56,"value":"\"Save\"","children":[{"start":57,"value":"Save","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":58,"pickleLine":58,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":59,"keywordType":"Context","textWithKeyword":"Given the user has just saved a document and the Document Detail View is open with saved name with star","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":60,"keywordType":"Context","textWithKeyword":"And The user is on the page with \"Edit\" and \"Actions\" buttons","stepMatchArguments":[{"group":{"start":29,"value":"\"Edit\"","children":[{"start":30,"value":"Edit","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Actions\"","children":[{"start":41,"value":"Actions","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":61,"keywordType":"Action","textWithKeyword":"When click \"Action\" button","stepMatchArguments":[{"group":{"start":6,"value":"\"Action\"","children":[{"start":7,"value":"Action","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":62,"keywordType":"Outcome","textWithKeyword":"Then The drop down contain\"Duplicate\", and Delete\"option will show","stepMatchArguments":[]}]},
  {"pwTestLine":65,"pickleLine":65,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":66,"keywordType":"Context","textWithKeyword":"Given The user is on the page with \"Edit\" and \"Actions\" buttons","stepMatchArguments":[{"group":{"start":29,"value":"\"Edit\"","children":[{"start":30,"value":"Edit","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Actions\"","children":[{"start":41,"value":"Actions","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":67,"keywordType":"Action","textWithKeyword":"When click \"Action\" Botton and selected\"Duplicate\"","stepMatchArguments":[{"group":{"start":6,"value":"\"Action\"","children":[{"start":7,"value":"Action","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":68,"keywordType":"Outcome","textWithKeyword":"Then Duplicate page created and listed in \"Creat Document\"page will display","stepMatchArguments":[]}]},
  {"pwTestLine":71,"pickleLine":71,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":72,"keywordType":"Context","textWithKeyword":"Given The user is on the page with \"Edit\" and \"Actions\" buttons","stepMatchArguments":[{"group":{"start":29,"value":"\"Edit\"","children":[{"start":30,"value":"Edit","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Actions\"","children":[{"start":41,"value":"Actions","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":73,"gherkinStepLine":73,"keywordType":"Action","textWithKeyword":"When user click \"duplicate \"page multiple time","stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":74,"keywordType":"Outcome","textWithKeyword":"Then Each duplicated page sholud be created  and listed in  \"Task page\"","stepMatchArguments":[{"group":{"start":55,"value":"\"Task page\"","children":[{"start":56,"value":"Task page","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":77,"pickleLine":77,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":78,"gherkinStepLine":78,"keywordType":"Context","textWithKeyword":"Given The user is on the page with \"Edit\" and \"Actions\" buttons","stepMatchArguments":[{"group":{"start":29,"value":"\"Edit\"","children":[{"start":30,"value":"Edit","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":40,"value":"\"Actions\"","children":[{"start":41,"value":"Actions","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":79,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When user click \"action\" and selected \"delete\" option","stepMatchArguments":[{"group":{"start":11,"value":"\"action\"","children":[{"start":12,"value":"action","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":33,"value":"\"delete\"","children":[{"start":34,"value":"delete","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":80,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then pop up will show with message\"Are you sure want to delete this record?\" with \"cancel\",and \"Proceed\" button.","stepMatchArguments":[{"group":{"start":77,"value":"\"cancel\"","children":[{"start":78,"value":"cancel","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":90,"value":"\"Proceed\"","children":[{"start":91,"value":"Proceed","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":81,"gherkinStepLine":81,"keywordType":"Outcome","textWithKeyword":"And user click \"Proceed\" button","stepMatchArguments":[{"group":{"start":11,"value":"\"Proceed\"","children":[{"start":12,"value":"Proceed","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":82,"keywordType":"Outcome","textWithKeyword":"And created task will delete and message will come\" record delet succesfully\"","stepMatchArguments":[]}]},
  {"pwTestLine":85,"pickleLine":85,"tags":["@document","@functional"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given User is on \"Create Document \"Page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":86,"gherkinStepLine":86,"keywordType":"Context","textWithKeyword":"Given The user is on \"Create Document\" page's  \"Other\" tab","stepMatchArguments":[{"group":{"start":15,"value":"\"Create Document\"","children":[{"start":16,"value":"Create Document","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Other\"","children":[{"start":42,"value":"Other","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":87,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When user click \"other\" tab","stepMatchArguments":[{"group":{"start":11,"value":"\"other\"","children":[{"start":12,"value":"other","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":88,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then save page will reload with botton \"Edit\",\"Action\".","stepMatchArguments":[{"group":{"start":34,"value":"\"Edit\"","children":[{"start":35,"value":"Edit","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":41,"value":"\"Action\"","children":[{"start":42,"value":"Action","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end